### ISSUE TITLE
[feature] Breadcrumb oder anpassbare Headline in EditMask

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#101]
Es wäre schön, wenn man in der EditMask die Möglichkeit hätte via Event ein Breadcrumb zu erzeugen oder die Headline vom DCA anzupassen. Gerade bei tierferen Verschachtelungen könnte man so eine besser Übersicht schaffen. Hier man ein Beispiel wie es mit der Breadcrumb aussehen würde:

![bildschirmfoto 2015-03-24 um 14 27 31](https://cloud.githubusercontent.com/assets/550207/6802561/eef5dcf4-d231-11e4-9ae0-acacc389d157.png)
Was denkt Ihr?

**Comment by discordier** [comment]
Dann mach einen PR der die Breadcrumb Methode der BaseView auch im edit mode usw. triggert und dann das Template entsprechend aufbohrt um selbigen dortens auch anzuzeigen.
