### ISSUE TITLE
Kind-Modell zeigt alle Einträge unabhängig vom Elternelement

### ISSUE THREAD

**Issue by seaneble** [contao-community-alliance/dc-general#104]
In einem aktuellen metamodel/core habe ich zwei Modelle definiert, die eine Eltern-Kind-Relation besitzen. Korrekterweise kann ich bei jedem Eltern-Eintrag auf eine Liste der Kind-Elemente springen.

Allerdings zeigt diese Liste stets alle Einträge der Kind-Tabelle an (und filtert nicht nach dem Eltern-Element). Zudem kann man neue Einträge anlegen, bei denen das pid-Feld in der Datenbank stets nur den Wert 0 erhält. Eine manuelle Änderung in der Datenbank bewirkt nichts, es tritt dennoch das Verhalten auf, dass die Kind-Elemente nicht gefiltert werden.

**Comment by seaneble** [comment]
@discordier hat Zugangsdaten zu einer der betroffenen Installationen erhalten. Tests führe auch ich gerne durch.

**Comment by MrTool** [comment]
sry wenn ich mich irren sollte aber hast du auch den mode umgestellt von flat auf hierarchical oder so?

**Comment by seaneble** [comment]
Das Problem war tatsächlich der fehlende "Render mode" "Parented" im Kind-Model.
