### ISSUE TITLE
Fatal Error - service Container is not passed to BaseSubscriber

### ISSUE THREAD

**Issue by amenk** [contao-community-alliance/dc-general#105]
I am getting the following error when accessing the backend using the last dev-develop version:

	Recoverable error: Argument 1 passed to MetaModels\DcGeneral\Events\BaseSubscriber::__construct() must implement interface MetaModels\IMetaModelsServiceContainer, none given, called in /home/example/local-workspace/misumi-europe.com/public/composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php on line 183 and defined in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BaseSubscriber.php on line 45
	#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BaseSubscriber.php(45): __error(4096, 'Argument 1 pass...', '/home/example/local...', 45, Array)
	#1 composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php(183): MetaModels\DcGeneral\Events\BaseSubscriber->__construct()
	#2 composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php(74): ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->addSubscribers(Object(Symfony\Component\EventDispatcher\EventDispatcher), Array)
	#3 system/modules/event-dispatcher/config/services.php(42): ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->configure(Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(Contao\Config))
	#4 composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php(43): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Symfony\Component\EventDispatcher\EventDispatcher))
	#5 system/modules/event-dispatcher/config/services.php(68): ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->create(Object(Closure), Object(Closure))
	#6 composer/vendor/pimple/pimple/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
	#7 composer/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
	#8 system/modules/metamodels/config/services.php(82): Pimple->offsetGet('event-dispatche...')
	#9 system/modules/metamodels/config/services.php(107): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
	#10 composer/vendor/pimple/pimple/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
	#11 composer/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
	#12 composer/vendor/metamodels/core/src/MetaModels/Helper/SubSystemBoot.php(93): Pimple->offsetGet('metamodels-serv...')
	#13 system/modules/metamodels/config/config.php(231): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
	#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
	#15 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(112): call_user_func(Object(Closure), Object(Pimple))
	#16 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(445): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
	#17 system/initialize.php(243): DependencyInjection\Container\ContainerInitializer->init()
	#18 contao/main.php(16): require('/home/example/local...')
	#19 {main}

	( ! ) Fatal error: Call to a member function getEventDispatcher() on a non-object in /home/example/local-workspace/misumi-europe.com/public/composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BaseSubscriber.php on line 95
	Call Stack

	...

**Comment by amenk** [comment]
installed:
	  cgo-it/news4ward-rateit                          dev-master 369516b News4ward-RateIt extension for the Contao Open Source CMS
	  cgo-it/rate-it                                   3.4.3              RateIt extension for the Contao Open Source CMS
	  cgo-it/xls_export                                3.0.0              xls_export extension for the Contao Open Source CMS
	  contao-community-alliance/composer-client        0.15.1             The contao composer client.
	  contao-community-alliance/composer-plugin        2.3.3              Composer plugin that provide contao integration and installer.
	  contao-community-alliance/dc-general             2.0.x-dev 02c33c0  Universal data container for Contao
	  contao-community-alliance/dependency-container   1.8.0              Dependency container based on pimple for Contao open source cms.
	  contao-community-alliance/event-dispatcher       1.4.x-dev d2da54a  Event dispatcher service for Contao Open Source CMS
	  contao-community-alliance/events-contao-bindings dev-master 4f9f928 Multipurpose translation manager and interface
	  contao-community-alliance/meta-palettes          1.9.4              MetaPalettes extension for Contao OpenSource CMS
	  contao-community-alliance/translator             1.0.1              Multipurpose translation manager and interface
	  contao-community-alliance/url-builder            1.1.2              General purpose URL builder and manipulator.
	  contao-legacy/ce_page_teaser                     1.5.3.9003         Artikelteaser und Seitenteaser zum Verlinken von Seiten statt Artikeln
	  contao-legacy/changelanguage                     2.2.8.9004         Allow the visitor to switch between different languages of a page.
	  contao-legacy/dlh_geocode                        1.0.4.9004         Geo coordinates for an address (for developers)
	  contao-legacy/dlh_googlemaps                     2.0.9.9003         Integration of Google Maps as a module
	  contao-legacy/efg                                2.2.1.9005         Manage form data: confirmation email, data storage, list and edit in backend and frontend
	  contao-legacy/om_searchkeys                      1.0.2.9007         Storage and analysis of search terms when using the contao search engine
	  contao-legacy/xls_export                         3.0.0.9016         PHP library to generate Microsoft Excel 95 files
	  contao/core                                      3.4.2              
	  discordier/justtextwidgets                       0.5.4              Hidden fields with text values and explanation texts
	  doctrine/cache                                   v1.4.0             Caching library offering an object-oriented API for many cache backends
	  leounglaub/contao-simple-ajax                    3.2.x-dev d1cebbe  More control over your AJAX requests.
	  menatwork/contao-multicolumnwizard               3.3.0              MultiColumWizard for Contao OpenSource CMS
	  metamodels/attribute_alias                       2.0.x-dev 8ceb316  MetaModels attribute for alias
	  metamodels/attribute_checkbox                    2.0.x-dev e8cd5c6  MetaModels attribute for checkbox
	  metamodels/attribute_combinedvalues              2.0.x-dev 6cc84e1  MetaModels attribute for combinedvalues
	  metamodels/attribute_country                     2.0.x-dev b7bb7fc  MetaModels attribute for country list
	  metamodels/attribute_decimal                     2.0.x-dev 439c582  MetaModels attribute for decimal values
	  metamodels/attribute_file                        2.0.x-dev 310e2c0  MetaModels attribute for files
	  metamodels/attribute_langcode                    2.0.x-dev 1334587  MetaModels attribute for langcodes
	  metamodels/attribute_longtext                    2.0.x-dev a35e7ae  MetaModels attribute for longtext
	  metamodels/attribute_numeric                     2.0.x-dev bec96de  MetaModels attribute for numeric values
	  metamodels/attribute_select                      2.0.x-dev 26d5a18  MetaModels attribute for selects
	  metamodels/attribute_tabletext                   2.0.x-dev 212e4c3  MetaModels attribute for dynamic table text
	  metamodels/attribute_tags                        2.0.x-dev afb66f1  MetaModels attribute for tags
	  metamodels/attribute_text                        2.0.x-dev 3023cd9  MetaModels attribute for selects
	  metamodels/attribute_timestamp                   2.0.x-dev a148da6  MetaModels attribute for timestamps
	  metamodels/attribute_translatedalias             2.0.x-dev 3f68cd8  MetaModels attribute for translated alias
	  metamodels/attribute_translatedcheckbox          2.0.x-dev 3813e42  MetaModels attribute for translated checkbox
	  metamodels/attribute_translatedcombinedvalues    2.0.x-dev 310be8e  MetaModels attribute for translated combinedvalues
	  metamodels/attribute_translatedfile              2.0.x-dev db05267  MetaModels attribute for translated files
	  metamodels/attribute_translatedlongtext          2.0.x-dev 52a3b75  MetaModels attribute for translated longtext
	  metamodels/attribute_translatedselect            2.0.x-dev 5753034  MetaModels attribute for translated selects
	  metamodels/attribute_translatedtabletext         2.0.x-dev e936db4  MetaModels attribute for dynamic translated table text
	  metamodels/attribute_translatedtags              2.0.x-dev 10ec358  MetaModels attribute for translated text
	  metamodels/attribute_translatedtext              2.0.x-dev 5744594  MetaModels attribute for translated text
	  metamodels/attribute_url                         2.0.x-dev 6e4d7b3  MetaModels attribute for urls
	  metamodels/bundle_all                            dev-master f589274 Universal MetaModels bundle
	  metamodels/bundle_attributes                     1.0.1              MetaModels bundle for all attributes
	  metamodels/bundle_filter                         1.0.0              MetaModels bundle for filter
	  metamodels/bundle_nontranslated                  1.0.3              MetaModels bundle for non translated attributes
	  metamodels/bundle_translated                     1.0.2              MetaModels bundle for translated attributes
	  metamodels/core                                  2.0.x-dev 8eaf7a7  MetaModels core
	  metamodels/filter_checkbox                       2.0.x-dev 7d06b8e  MetaModels checkbox filter
	  metamodels/filter_fromto                         2.0.x-dev d84ea15  MetaModels fromto filter
	  metamodels/filter_range                          2.0.x-dev 3516f56  MetaModels range filter
	  metamodels/filter_select                         2.0.x-dev 5978066  MetaModels select filter
	  metamodels/filter_tags                           2.0.x-dev 1127e52  MetaModels tags filter
	  metamodels/filter_text                           2.0.x-dev 6df9de1  MetaModels text filter
	  pimple/pimple                                    v1.1.1             Pimple is a simple Dependency Injection Container for PHP 5.3
	  psi/news4ward                                    2.2.3              A blogging / news system for Contao
	  psi/news4ward_archive-menu                       2.0.8              Archive menu frontend module for News4ward
	  psi/news4ward_author-menu                        2.0.2              Archive menu frontend module for News4ward
	  psi/news4ward_comments                           2.1.0              Comments integration for News4ward
	  psi/news4ward_metatitle                          1.1.0              MetaTitle addon for News4ward
	  psi/news4ward_mostread                           2.1.0              Read hit counter for News4ward
	  psi/news4ward_multicategories                    1.0.4              Multi-Categories menu frontend module for News4ward
	  psi/news4ward_related                            2.1.0              Related articles for News4ward
	  psi/news4ward_tags                               2.1.1              Tags and tagcloud for News4ward
	  psi/tags-widget                                  2.0.6              Contao Widget for managing Tags
	  symfony/event-dispatcher                         v2.6.5             Symfony EventDispatcher Component
	  symfony/expression-language                      v2.6.5             Symfony ExpressionLanguage Component

**Comment by discordier** [comment]
Das Problem hat sich erledigt, es waren noch Reste eines nightly vorhanden.
