### ISSUE TITLE
MM unter 3.5.0-beta1 funktioniert (bei mir) nicht

### ISSUE THREAD

**Issue by KlausGrenoble** [contao-community-alliance/dc-general#106]
Ich hab' mal contao  3.5.0-beta1 neu aufgesetzt. Bei mir kommt im Backend bei Aufruf eines MetaModels
```
Fatal error: Class ContaoCommunityAlliance\DcGeneral\DC_General contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Contao\DataContainer::getPalette, Contao\DataContainer::save) in /home/users4/k/klaus/www/galerie/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DC_General.php on line 370
```
https://community.contao.org/de/showthread.php?56457-MM-unter-3-5-0-beta1-funktioniert-(bei-mir)-nicht

Gruss Klaus

**Comment by discordier** [comment]
Problem introduced in https://github.com/contao/core/commit/e674beac7645b367dacf63e4336abe783b7aab1c#diff-185a6a75444b4e73f516f3094fc7eb11R22

We need some more empty methods... :(

**Comment by tim-bec** [comment]
@discordier @stefanheimes oder @dmolineus könntet ihr mal schauen ob das kurzfristig lösbar ist? ich stoß da mit mm und synccto drauf. nennt mir gern auch nen preis...

**Comment by dmolineus** [comment]
@tim-bec Hab dazu einen PR gemacht. Wenn dies alles ist für die Compat 3.5, passt es so.

**Comment by discordier** [comment]
Works for me.
