### ISSUE TITLE
TreePicker not working

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#108]
As discuessed here: https://github.com/contao-community-alliance/dc-general/issues/107 I started to try the DcGeneralTreePicker. But I get the following error ...

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Definition properties is not registered in the configuration tl_postmanager_post. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/DefaultContainer.php on line 141

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/DefaultContainer.php(202): ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer->getDefinition('properties')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(117): ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer->getPropertiesDefinition()
#2 system/modules/dc-general/backend/generaltree.php(32): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#3 {main}
```

My configuration looks like this:

```
'category'                 => array(
            'label'     => &$GLOBALS['TL_LANG']['tl_news']['categories'],
            'exclude'   => true,
            'inputType' => 'DcGeneralTreePicker',
            'eval'      => array
            (
                'sourceName' => 'tl_page',
                'fieldType'  => 'checkbox',
                'title' => 'title'
            ),
            'sql'       => "blob NULL"
        ),
```
I also tested it with the attribute_tags from MetaModels, same error. @discordier can you have a look on it?

**Comment by discordier** [comment]
Eh, for `tl_page` Contao has the `PagePicker` which does a whole lot extra stuff.

It appears that the data container is not correctly built.

**Comment by cboelter** [comment]
Your are right, for tl_page I can use the PagePicker-Widget. But with other Tables I Have the same problem.

**Comment by discordier** [comment]
Then thus has to be fixed. I guess it is somewhere in the definition builder and not in the picker as it works for MetaModels.

**Comment by stefanheimes** [comment]
It seems to be a problem with the backend boot from MetaModels. All Events for the PreCreateDcGeneralEvent are missing. So the DcGeneralTreePicker have no class wich build the definition.

**Comment by stefanheimes** [comment]
Change the handling with 3e57a00d33dee48eefee09da2a4650f58087330e

**Comment by discordier** [comment]
No feedback, closing therefore.
