### ISSUE TITLE
Beim kopieren werden Einträge nicht umbenannt

### ISSUE THREAD

**Issue by HellPat** [contao-community-alliance/dc-general#109]
In meinem Fall bei Metamodels.

Ich dupliziere ein Rendersetting.
Danach sieht das so aus:

![bildschirmfoto 2015-04-10 um 12 18 11](https://cloud.githubusercontent.com/assets/1016798/7085925/cd9cb77e-df7b-11e4-98cb-3bbd06054063.png)

ich weiß nun nicht welches das schon verwendete ist, und welches das neue.
(Außer ich schaue mir die ID an)

Mein Vorschlag ist, wie bei Contao den Namen auf _1 _2 etc. zu setzen.

**Comment by discordier** [comment]
Besser waere es beim duplicate in die edit maske zu wechseln, denn wie will man definieren welche properties nun suffixed werden sollen. Zumal das bei selects usw. nicht einmal moeglich ist.

**Comment by xantippe** [comment]
könnte man nicht wie bei Contao-Core ein "(Kopie)" hinten ansetzen - wer das nicht möchte, könnte das "DCA-Konform" auch abschalten

**Comment by zonky2** [comment]
aktuell (DCG-b34) gibt eine Fehlermeldung beim Duplizieren von Render-Einstellungen oder Eingabemasken

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 118

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber.php(338): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber->initializePanels(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```

ein Ansatzpunkt für das Hinzufügen des "(Kopie)" wäre z.B. in https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php#L462-L489
mit 

```diff
    private function handleClonedModelProperty(
        ModelInterface $model,
        PropertyInterface $property,
        DataProviderInterface $dataProvider
    ) {
        $extra    = $property->getExtra();
        $propName = $property->getName();

        // Check doNotCopy.
        if (isset($extra['doNotCopy']) && $extra['doNotCopy'] === true) {
            $model->setProperty($propName, null);
            return;
        }

        // Check fallback.
        if (isset($extra['fallback']) && $extra['fallback'] === true) {
            $dataProvider->resetFallback($propName);
        }

        // Check uniqueness.
        if (isset($extra['unique'])
            && $extra['unique'] === true
            && !$dataProvider->isUniqueValue($propName, $model->getProperty($propName))
        ) {
            // Implicit "do not copy" unique values, they cannot be unique anymore.
            $model->setProperty($propName, null);
        }
        
+        // Add '(Copy)' to property 'name'.
+        if ($propName == 'name') {
+          $model->setProperty($propName, sprintf($GLOBALS['TL_LANG']['MSC']['copyOf'], $model->getProperty($propName)));
+        }
    }
```

wobei hier eine "feste Verdrahtung" zu 'name' wäre - lt. @baumannsven hat @discordier eine flexiblere Lösung im Blick...

**Comment by asaage** [comment]
Das selbe Problem besteht auch bei ModelItems (In deinem Fall wären das dann wohl "Mitarbeiter").
Vielleicht kann man sich generell auf eine "feste Verdrahtung" zu 'name' festlegen!?

**Comment by baumannsven** [comment]
Dieser hotfix müsste das Problem lösen.
https://github.com/contao-community-alliance/dc-general/pull/213

**Comment by baumannsven** [comment]
Hier würde ich vorschlagen das property dem der Kopierhinweis angehängt werden soll im config zu konfigurieren.

$GLOBALS['TL_DCA']['thisTable']['config']['copyProperty'] = 'title';

@discordier , @stefanheimes Was meint ihr dazu?

**Comment by discordier** [comment]
Kein Fan davon...

1. Damit haben wir wieder Zeugs im DCA, welches in den Container an die property config gehoert.
2. Es ist nicht klar WAS an der Property modifiziert werden soll (suffix, prefix, infix, whatever).

Das sollte man nochmal genauer yberdenken.

**Comment by baumannsven** [comment]
Wenn ich dich richtig verstanden, meinst du im Field config.
Dort könnte man das mit sprintf wie z.b. beim Label Formatter lösen.

**Comment by discordier** [comment]
Ja, theoretisch ist das moeglich, aber dann nicht aus dem Code heraus auf das DCA zugreifen sondern einen neuen Getter an die PropertyDefinition anbauen.

**Comment by baumannsven** [comment]
@discordier 

Diesen Gedanken hatte ich auch. Dann werde ich mich darum kümmern, wenn ich mit dem finalen Deep Copy fertig bin.

**Comment by zonky2** [comment]
@baumannsven kommt das nach dem edit/overrideAll "auf den Tisch" ;-)

**Comment by baumannsven** [comment]
@zonky2 Ja das kommt dann mit dem final deep copy

**Comment by zonky2** [comment]
o.k. - dann verbinde ich das mal mit https://github.com/contao-community-alliance/dc-general/issues/191

**Comment by zonky2** [comment]
> Besser waere es beim duplicate in die edit maske zu wechseln, denn wie will man definieren welche properties nun suffixed werden sollen. 

DCG 2.3: das ist der Fall auch bei MM-Items wie Mitarbeiter
