### ISSUE TITLE
TagsWidget does not work correctly

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#112]
I tried to use the TagsWidget (https://github.com/psi-4ward/tagsWidget) with the DcGeneral. Works fine in general. But I can't delete all tags. If I do this, it will "restore" the last values before deleting. 
In normal DcTable it works fine.
@discordier could you have a look on it?

**Comment by discordier** [comment]
Should be fixed with c3954ad993a8e68c9b574868c0d262e5daae89f2.

**Comment by discordier** [comment]
Assuming to be fixed as no response.
