### ISSUE TITLE
FileUpload-Widget does not work

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#113]
The FileUpload-Widget from contao does not work with DcGeneral. I added the widget this way ...

```
'teaser_image'                   => array
        (
            'label'     => &$GLOBALS['TL_LANG']['tl_postmanager_post']['name'],
            'exclude'   => true,
            'inputType' => 'fileUpload',
            'eval'      => array
            (
                'tl_class'  => 'long',
                'uploadFolder' => 'files'
            ),
            'sql'       => "blob NOT NULL"
        ),
```

Works fine in DcTable but not in DcGeneral.
I had a look into https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L770 and it seems that there is no property `teaser_image` in the PropertyValueBag.

**Comment by zonky2** [comment]
@baumannsven current status?

**Comment by baumannsven** [comment]
This must be testing.

**Comment by baumannsven** [comment]
@cboelter Can describe your test case?

**Comment by zonky2** [comment]
there is the question whether a separate upload button in the BE is necessary - with the filepicker popup you can also upload files directly... since Contao 4.8 also directly via D&D

**Comment by baumannsven** [comment]
This has been fixed long time ago.
