### ISSUE TITLE
Manuelle Sortierung - Sorting-Wert wächst rasant / übersteigt Maximum

### ISSUE THREAD

**Issue by pju-** [contao-community-alliance/dc-general#149]
Bezieht sich auf [diesen Forenthread.] (https://community.contao.org/de/showthread.php?57106-Metamodel-Datenbank-quot-sorting-quot&p=378965#post378965)

Aktuelle Nightly (2015-07-30), Contao 3.5.0, dc-general dev-develop @ efcc6d 2015-07-28 23:27:28

Bei manueller Sortierung steigen die Sorting-Nummern in der Datenbank in sehr hohen Sprüngen. Dadurch läuft das Datenbank-Feld sorting schnell voll, weil der Maximalwert erreicht ist. Danach lässt sich die Sortierung nicht mehr ändern.

Das sorting springt auch, wenn nur zwei Werte getauscht werden. 

Beispiel:

Vorher:
<img width="686" alt="bildschirmfoto 2015-07-30 um 14 18 06" src="https://cloud.githubusercontent.com/assets/5202770/8982926/0d21fb92-36c6-11e5-8c4c-8231c83f2bd6.png">

Nachher (Item e verschoben, neu vor d): 
<img width="686" alt="bildschirmfoto 2015-07-30 um 14 19 08" src="https://cloud.githubusercontent.com/assets/5202770/8982927/0d22d99a-36c6-11e5-8a69-b2365cfe3f59.png">

**Comment by cyberlussi** [comment]
Es ist mir auch schon aufgefallen, dass die Sorting-Werte schnell steigen. Wenn man die sorting-Werte nach einem Sortieren "aufräumen" würde (1-2-3-4-5 .... oder vielleicht 100-200-300), wäre das Problem gebannt.

**Comment by discordier** [comment]
@pju-, @cyberlussi The fix has been merged. Could you please test again with current develop?

**Comment by cyberlussi** [comment]
contao-community-alliance/dc-general 	dev-develop (dfca095e)
metamodels/core 	dev-master (4bcb7e12)

Ich habe 5 Einträge im MM, wenn ich "auf gut Glück" sortiere, bleiben die sorting Werte immer <= 640. Wenn ich aber *immer* einen Eintrag "nach unten" umsortiere, wachsen stetig alle sorting Werte. Bis INT(10) erreicht ist, dauert das doch schon etwas, aber aktuell habe ich durch manuelles Sortieren auch schon Werte zw. 7552 und 8064. Wenn man dann ein paar Einträge "nach oben" umsortiert lande ich wieder zw. 128 und 640.

Wenn ich direkt in die Datenbank 4294967295 als sorting-Wert des letzten Eintrages einfüge (um zu simulieren, dass gaaaanz oft nach unten umsortiert wurde) und dann einen anderen Eintrag "nach unten" umsortiere, hat dieser neue Sorting-Wert auch das maximum 4294967295 (i.e. Sortierung schlägt fehl). 

Funktion is prinzipiell okay, aber 100% sicher ist es nicht. Vielleicht sollte doch vor Erreichen des Maximums, die Sortierung zu kleineren Werten korrigiert werden.

**Comment by pju-** [comment]
I can confirm what @cyberlussi said so far.

**Comment by discordier** [comment]
Es wachsen immer die Werte ab dem nachfolgenden der neuen Position, oder?

Da kann man durchaus noch etwas nacharbeiten, aber das Problem sollte nun eigentlich so gut wie nie mehr auftreten, da man seltenst pauenlos den ersten ans Ende schiebt.

**Comment by cyberlussi** [comment]
Kann ich so bestätigen. Wie gesagt. Funktion gegeben, solange man nicht tausende Mal immer nur "nach unten" umsortiert - kommt sicherlich auch auf die Anzahl der Einträge in der Tabelle an. Die Sprünge sind auf jeden Fall kleiner als vorher.

**Comment by xantippe** [comment]
wäre es möglich, dass bei einem bestimmten Schwellwert von "sorting" die Zahlen automatisch "geglättet" werden? 

@discordier wir hatten uns ja schon mal über ein "DB-Tool-Panel" unterhalten, mit dem bestimmte DB-Bereinigungen (tote Relationen, Doppelte Einträge bei Unique, usw.) behandelt werden können - dort könnte man die "Glättung" auch manuell anstossen

**Comment by discordier** [comment]
Koennte man theorethisch machen, ist bislang jedoch nicht angedacht.

**Comment by discordier** [comment]
I close this ticket. Please open a feature request for the new feature of reducing the values if the issue should come up again.
