### ISSUE TITLE
Catch exceptions in ContaoWidgetManager::[en/de]codeValue()

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#15]
`ContaoWidgetManager::[en/de]codeValue()` is triggering the event for encoding values.

We need to put some safe constraints in there, as the old save_callbacks may throw exceptions.

I am unsure as of how to handle them, as the event propagation will stop after the first exception.
Maybe we need another property "errors" in the `EncodePropertyValueFromWidgetEvent` and `DecodePropertyValueForWidgetEvent` which will get filled by the `PropertyOnLoadCallbackListener` and `PropertyOnSaveCallbackListener` whenever an exception is raised.

**Comment by zonky2** [comment]
@discordier what is your question..?

**Comment by discordier** [comment]
No a question at all. This is just a reminder ticket that exceptions must be catched.

However, I do not know offhand if they still aren't catched in the current code base. We'll have to check.

**Comment by baumannsven** [comment]
Fixed in 88737b233730f298d5f34729da0dd942685aa8f8
