### ISSUE TITLE
Manuelle Sortierung - Verschieben auf erste Position nicht möglich

### ISSUE THREAD

**Issue by pju-** [contao-community-alliance/dc-general#150]
Aktuelle Nightly (2015-07-30), Contao 3.5.0, dc-general dev-develop @ efcc6d 2015-07-28 23:27:28

Situation: Bei der Eingabemaske ist showColumns ausgewählt, so dass über den Items noch ein Header kommt.

Wenn man jetzt ein Item so verschiebt, dass es neu an erster Stelle steht, ändert sich nichts. Sobald man die Seite aktualisiert, steht das Item wieder an der vorherigen Stelle. Im DB-Feld sorting ändert sich auch nichts.

Wenn man stattdessen das erste Item nach unten schiebt, funktioniert es.

Um ein Element an die erste Stelle zu verschieben, muss man es ÜBER dem Header ablegen. Das ist aber vermutlich nicht so gedacht.

<img width="896" alt="bildschirmfoto 2015-07-30 um 20 35 45" src="https://cloud.githubusercontent.com/assets/5202770/8991715/b686585c-36fa-11e5-92c0-c77b15a902dd.png">

**Comment by dmolineus** [comment]
@amenk Do you maybe want to have a look at it as you are working on the showColumns feature?

**Comment by amenk** [comment]
no time ATM, sorry

**Comment by xantippe** [comment]
man kann an die erste Stelle verschieben

vorher:
![shot79](https://cloud.githubusercontent.com/assets/1045318/12530534/f7b10ca6-c1e1-11e5-8708-ee94f6b6be95.jpg)

nachher:
![shot80](https://cloud.githubusercontent.com/assets/1045318/12530536/0019abd2-c1e2-11e5-9f62-f9aa55714bf4.jpg)

** es ist aber auch möglich, über die Kopfzeile zu schieben** nach reload ist Kopfzeile wieder am richtigen Platz...

![shot81](https://cloud.githubusercontent.com/assets/1045318/12530542/253ed70c-c1e2-11e5-91cb-cb058615388d.jpg)

**Comment by xantippe** [comment]
Verschieben über die Kopfzeile wird hiermit gefixt: #180 

wenn der PR drin ist, kann m.E. das Ticket geschlossen werden
