### ISSUE TITLE
Sorting without grouping doesn't work

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#154]
Sorting is then always the ID and not the configured attribute (in my case text).

regards

**Comment by dmolineus** [comment]
I know what's the issue. Propably better to discuss it @discordier how to solve.

**Comment by discordier** [comment]
@dmolineus So tell me. :)

**Comment by arillus-at** [comment]
even sorting with grouping doesn't work.
It doesn't matter if text or decimal, please have a look at the screenshots

https://www.sendspace.com/file/su17t1

**Comment by discordier** [comment]
@arillus-at Could you please embedd screenshots here in github instead of publishing them in a word document? It makes things a whole lot more easy for us.

However, the issue should be fixed by the merge of #155 now. @ainschy can you confirm?

**Comment by Ainschy** [comment]
sorting with "Do not group" doesn't work.

**Comment by dmolineus** [comment]
Now I bet metamodels/core causes the issue. The sorting is not set when being in group mode none:

https://github.com/MetaModels/core/blob/master/src/MetaModels/DcGeneral/Dca/Builder/Builder.php#L1070-L1081

**Comment by discordier** [comment]
I remember this. The reason was that dcg can not handle sorting if the grouping property differs from the sorting property.

**Comment by dmolineus** [comment]
I was wrong. It is MM, provided a PR for that.

**Comment by cyberlussi** [comment]
Great - works for me now! Grouped and not grouped; and together with a filter.

**Comment by asaage** [comment]
:thumbsup:
