### ISSUE TITLE
CSS-Klassen im ListView vereinheitlichen

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#160]
In der Listenansicht showColumns werden verschiedene CSS-Klassen den einzelnen Zellen mit auf den Weg gegeben - möchte man im BE per CSS eigene Hervorhebungen machen, würde eine einheitlichere Klassenvergabe die Aufgabe vereinfachen.

Im Kopf der Tabelle (th-Tags) werden die Klassen `tl_folder_tlist` sowie `col_<name>` vergeben

Im Body der Tabelle (td-Tags) die Klassen `tl_file_list` sowie `col_<#>`

Warum "folder" und "file" auftauchen? Die Differenzierung zwischen Head und Body ist mit den Tags gegeben - tl_folder_tlist und tl_file_list m.E. nicht zwingend notwendig.

Leider gibt es für die Spalten keine eingeitliche Klasse - im Head `col_<name>` vs. im Body `col_<#>`

Ich würde eine einheitliche Bezeichnung `col_<name>` wählen, da man hier eine Formatierung abhängig vom Attribut(Name) machen kann - die Spaltennummer kann inzwischen gut per CSS-Selektor abgefangen werden.

**Comment by discordier** [comment]
Dass die unterschiedlich sind ist in der Tat ein bug.

**Comment by discordier** [comment]
Die Klassen `tl_folder_tlist` und `tl_file_list` myssen wir nochmal diskutieren, denn die erben ja das Contao CSS, welches durch entfernen derselbigen dann nicht mehr zum tragen kommen.

**Comment by zonky2** [comment]
at table view wie have ```col_<name>```at header and body - looks good

the table tag have id name with ```_``` as last character? like ```<table id="table_mm_mitarbeiterliste_" class="tl_listing showColumns">```

**Comment by zonky2** [comment]
and works fine
