### ISSUE TITLE
Popup-Tags werden nicht übernommen

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#161]
Fehler ist aufgetreten bei MetaModels, wenn hier versucht wird im Fenster vom GeneralTreePicker eine Mehrfach Auswahl zu übernehmen, gibt es einen JS Fehler.

Siehe: https://github.com/MetaModels/core/issues/883

**Comment by siemendev** [comment]
Ist dieses Update jetzt schon durch eine Paketaktualisierung nutzbar?

**Comment by stefanheimes** [comment]
Folgende Versionen enthalten der Commit:  develop  2.0.0-beta31  2.0.0-beta30 2.0.0-beta29

**Comment by discordier** [comment]
Assuming fixed.
