### ISSUE TITLE
tree_xtnd toggler injects at wrong dom-position

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#168]
In Hierarchy-input-screen extending a node with 30+ childnodes places them on-top of the parent and not below. If you refresh the page the parent-node is expanded correctly.

Original: https://github.com/MetaModels/core/issues/918

**Comment by stefanheimes** [comment]
Duplicate see https://github.com/contao-community-alliance/dc-general/issues/89

**Comment by xantippe** [comment]
funktioniert bei "allen" ```DC General Tree BackendView Ultimate``` in MM nicht korrekt
