### ISSUE TITLE
Filter im Backend (oben) funktionieren nicht bei referenzierten MM

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#18]
Grundlage zwei MM:
1. MM Kategorien
2. MM Items
Beim 2. MM würde ich jetzt gerne nach Kategorien suchen können, die den Items zugewiesen sind. Das geht aber nur über die ID von den Kategorien, nicht mit Texteingabe.

**Comment by Aybee** [comment]
Bin mir nicht ganz sicher, ob ich hier das Gleiche habe.

Die Filter im BE oben im Panel filtern zwar, aber bei Filtern wo die Werte aus einem anderen MM kommen (multi select) wird nach dem Filtern nicht die Auswahl angezeigt, sondern der Feldname.

Beispiel:
**Name** (Textfeld)
- Andreas
- Frank

Ich filtere nach Andreas und dann steht oben im Select "Andreas"

**Produkte** (multiselect)
- Gemüse
- Obst

Ich filtere nach Gemüse, der Filter filtert auch richtig, aber oben im Filter steht "Produkte".

Ich vermute, dass hier einfach das "selected" nicht auf die gefilterte OPTION aufgesetzt wird.

Contao 3.4.5 `contao-community-alliance/dc-general             dev-develop @ a69951    2015-05-05 07:49:00`

**Comment by xantippe** [comment]
MM 2.0.0a10 + DCG 2.0.0b34 getestet mit [select]

![shot108](https://cloud.githubusercontent.com/assets/1045318/13180214/d3262c08-d727-11e5-9cee-a7fa2e77b559.jpg)
