### ISSUE TITLE
Bildvorschau-Generierung

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#181]
die Generierung der Bildvorschau für das Backend
https://github.com/contao-community-alliance/dc-general/blob/388f7a7cf7d2e40a37cac691d860e90dfe889bfe/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php#L251
prüft, ob das Bild kleiner-gleich der max. eingestellten Bildgröße ist - was ist, wenn per FTP ein größeres Bild hochgeladen wurde?

m.E. muss hier jeweils eine Größe für die "minimale Größe" angegeben werden und geprüft, ob das Bild kleiner ist...

```diff
-        if ($file->isSvgImage
-            || $file->height <= \Config::get('gdMaxImgHeight') && $file->width <= \Config::get('gdMaxImgWidth')
-        ) {
-            $image = \Image::get($model->path, 80, 60, 'center_center');
-        }

+        $intMinImgWidth  = 80;
+        $intMinImgHeight = 60;
        
+        if ($file->isSvgImage
+            || $file->height > $intMinImgHeight || $file->width > $intMinImgWidth
+        ) {
+            $image = \Image::get($model->path, 80, 60, 'center_center');
+        }
+        else
+        {
+            $image = $model->path;
+        }

```

für ein 16x16-Icon:
vorher:
![shot84](https://cloud.githubusercontent.com/assets/1045318/12574823/c77190b0-c407-11e5-9cb6-813c2fdabb02.jpg)

nachher (mit Quelltextänderung wie oben angegeben):
![shot83](https://cloud.githubusercontent.com/assets/1045318/12574846/dba2e156-c407-11e5-9fcb-dd53667fce29.jpg)

**Comment by dmolineus** [comment]
Schau ich mir an.

**Comment by xantippe** [comment]
ggf. die "Min-Parameter" konfigurierbar über DCA o.ä. machen und mit in "\Image::get.." rein ziehen

**Comment by xantippe** [comment]
https://github.com/contao-community-alliance/dc-general/commit/93c3271117f0b12913282b91865261b73e9d39ae#commitcomment-16208298

**Comment by zonky2** [comment]
implemented https://github.com/contao-community-alliance/dc-general/pull/208
