### ISSUE TITLE
FR: Sprachwähler auch bei Listenansicht im BE (für MM)

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#189]
Es wäre schön, wenn man bei MM in der Listenansicht nicht nur die Ausgabe in der Standard/Fallback-Sprache hätte, sondern hier auch die Sprache umschalten könnte (analog der Eingabemaske).

**Comment by discordier** [comment]
Ich verstehe den FR nicht.

Du willst in der DCG Liste analog zum edit view den language selector?

**Comment by zonky2** [comment]
Ja!

Beim Eingeben oder Suchen ist es nach meiner Erfahrung hilfreich, die 
Listenwerte auch in den übersetzten Sprachen sehen zu können. Man sieht dann auch schnell was von den Sachen übersetzt ist und was nicht...

**Comment by zonky2** [comment]
added in DCG 2.1

**Comment by baumannsven** [comment]
Fixed in 3df7d26f88a2ce4fedd10e7c2279a134653094b1
