### ISSUE TITLE
composer require contao-community-alliance/url-builder

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#190]
@discordier 
Es wird die Klasse ContaoCommunityAlliance\UrlBuilder\Contao\BackendUrlBuilder benutzt.
https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L127

Dann müsste ja in den requirements von composer das packet "contao-community-alliance/url-builder"
registriert werden.

**Comment by discordier** [comment]
Fixed in f0e1348f62fb8952a8860773c2ac57f37cc407e1
