### ISSUE TITLE
Filtern von Tags im BE führt zu keinem Ergebnis

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#194]
Filtern von Tags im BE führt zu keinem Ergebnis MM alpha10 DCG beta34

Suche von Tags geht

**Comment by discordier** [comment]
Was ist gewynscht?
Was passiert statt dessen?

**Comment by xantippe** [comment]
es wird nicht gefiltert, d.h. die "Gesamtmenge der  Items wird nicht auf die Teilmenge verkleinert"
gewünscht wäre, dass genau das passiert (analog beim Filtern von z.B. Select-Attributen)

**Comment by discordier** [comment]
Und wie soll das bei tags sein? Alle anzeigen die das Tag "besitzen"? Mehrere kann man hier ja nicht auswaehlen (anders als wie im FE). Daher kann man maximal nach einem filtern.

Ich pack es mal auf die roadmap von 2.0.0, damit wir es uns ansehen.

**Comment by xantippe** [comment]
ich würde sagen ja, zeige die an, wo Tag gesetzt...

**Comment by zonky2** [comment]
funktioniert (doch)

getestet mit 
* metamodels/core 	2.0.0-alpha10
* metamodels/attribute_tags 	2.0.0-alpha6
* contao-community-alliance/dc-general 	2.0.0-beta34
