### ISSUE TITLE
BE: Suche-Select bekommt nach Suche kein "selected"-Attribut

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#196]
BE: Suche-Select bekommt nach Suche kein "selected"-Attribut - daher sieht man nicht (mehr) nach was man gesucht hat...

![shot109](https://cloud.githubusercontent.com/assets/1045318/13181860/56cd2032-d72f-11e5-92b6-4270a675664f.jpg)

**Comment by discordier** [comment]
@dmolineus When will you have time for this?

**Comment by xantippe** [comment]
PR is ready https://github.com/contao-community-alliance/dc-general/pull/210

**Comment by zonky2** [comment]
include in 2.0.0-beta35
