### ISSUE TITLE
Anzeigefehler im BE bei Renderlisting "Tabelle" und Sortierung mit einer Gruppierung: HTML-Table fehlt

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#198]
siehe https://github.com/MetaModels/core/issues/936

Ist in der Renderansicht einer Eingabemaske "Tabellendform" angegeben und eine Gruppierung ausgewählt, fehlt in der Anzeige die "HTML-Tabelle"

der "Fehler" liegt eher an dem bei der Anzeigekombination ausgewählten Template - dcbe_general_grouping in https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php#L276 welches mit der Tabellenansicht nicht zurecht kommt.

In dem Screenshot nochmal eine Zusammenstellung welche Anzeigenkombination möglich ist und welche sich ausschließt

![shot127](https://cloud.githubusercontent.com/assets/1045318/13279105/7b1f26c0-dad5-11e5-891d-3f2a4c59b7a2.jpg)

unter der Maßgabe, dass sich bei einer Gruppierung keine manuelle Sortierung vornehmen lassen kann - **oder sollte das auch ermöglicht werden?**

Der aktuelle Aufbau des Templates für die Gruppierung ist nicht geeignet für eine Tabellenansicht. Der Aufbau ist i.E. so

```
<table>
  <tr>Header...</tr>
</table>
<div>Gruppierungsüberschrift 1</div>
<table>
  <tr>Item 1</tr>
  <tr>Item 2</tr>
</table>
<div>Gruppierungsüberschrift 2</div>
<table>
  <tr>Item 3</tr>
  <tr>Item 4</tr>
</table>
```

Ein Vorschlag wäre, eine durchgängige Tabelle und die Inhaltlichen Blöcke mittels eigener `body`-Bereich abzugrenzen - lt. W3C sind mehrere bodies bzw. `tbody` erlaubt
siehe http://www.w3schools.com/tags/tag_tbody.asp - in tbody ist nach http://www.w3schools.com/tags/ref_standardattributes.asp auch die Verwendung von Attribut ID erlaubt - die Angabe wird z.Z. den Gruppen-Einzeltabellen zugeordnet

Die Tabelle würde dann i.E. so aussehen:

```
<table>
  <thead>
    <tr>Header...</tr>
  </thead>
  <tbody>
    <tr><Gruppierungsüberschrift 1</tr>
  </tbody>
  <tbody>
    <tr>Item 1</tr>
    <tr>Item 2</tr>
  </tbody>
  <tbody>
    <tr><Gruppierungsüberschrift 2</tr>
  </tbody>
  <tbody>
    <tr>Item 3</tr>
    <tr>Item 3</tr>
  </tbody>
</table>
```

(Hinweis: dcbe_general_grouping ist auch für die "normale" BE-Auflistung vom DCG bzw. MM zuständig)

**Comment by discordier** [comment]
@MacKPWD could you jump in on this one?

**Comment by MacKP** [comment]
Here is a better code for this:
’’’
<table>
  <thead>
    <tr>Header...</tr>
  </thead>
  <tbody>
<tr>
   <th colspan="2" scope="colgroup">
<Gruppierungsüberschrift 1>
</th>
</tr>
    <tr>Item 1</tr>
    <tr>Item 2</tr>
    <tr>
   <th colspan="2" scope="colgroup">
<Gruppierungsüberschrift 2
</th>
</tr>
    <tr>Item 3</tr>
    <tr>Item 3</tr>
  </tbody>
</table>
’’’

Note: 
- only one <tbody> for all.
- in the <tr> for the Grouping-Headline take an <th> with colspan and colgroup.

Look here for more Informations: https://www.w3.org/WAI/tutorials/tables/multi-level/#table-with-three-headers-related-to-each-data-cell

regards

**Comment by xantippe** [comment]
da gehe ich mit - prüfen das aber noch mal mit Nina ab...

**Comment by discordier** [comment]
@MacKP This will break the existing javascript code which limits manual sorting to the current grouping, therefore this needs to be adjusted (but according to @xantippe above, this is currently broken anyway).

I am in general fine with either HTML representation, whichever makes more sense to you frontend guys.

**Comment by xantippe** [comment]
@discordier Gruppierung und manuelle Sortierung zusammen sind m.E. zusammen nicht aktiv - siehe Tabelle oben...

**Comment by discordier** [comment]
I read your comment above but can not verify atm. Therefore this must get fixed along if it is not working yet. It definately was intended to work and be supported but must have got lost somewhere during the fixes lately.

**Comment by MacKP** [comment]
The Code i have posted should be the best one for this situation. The code from xantippe is just without any sense...
regards

**Comment by NinaG** [comment]
Die wichtigste Regel (Usability/Accessibility) im Umgang mit Tabellen: 
Sobald Tabellen kompliziert werden, ist es Zeit, sie aufzuteilen.

So wie ich das sehe, ist das hier ein idealer Zeitpunkt dafür, wenn schon mit Tabellen-Zwischen-Zwischenüberschriften und sowas gearbeitet wird.

Sprich: Könnt ihr nicht einfach normal mit <Hx> Zwischenüberschriften machen und dann jeweils eine passende neue Tabelle anfangen? So wird das leichter visuell/strukturell für Nutzer zu erfassen und ist weiterhin semantisch.

**Comment by MacKP** [comment]
@NinaG das war auch meine erste Idee. So ist das fast auch aktuell (allerdings leider ein `<div>` anstelle von einer Überschrift). Allerdings hast man dann das Problem, wenn die Tabellen nicht viel Inhalt haben, das man dann massiv viel Overhead hat mit Tabellenüberschriften (die ja dann für jeden Block neu geschrieben werden). Zusätzlich findet Zonky das nicht so prall, da die dann ja unterschiedlich Breite Inhalte haben und das deswegen nicht so schön aussieht ;-)

**Comment by NinaG** [comment]
Die Optik lässt sich leicht über CSS-Klassen steuern, die dafür sorgen, dass die Spalten jeweils in den Tabellen passend aussehen.

Das bisschen Overhead finde ich auch ok, wenn dafür die Usability deutlich besser ist, als bei einer verschachtelten Monstertabelle. 

Wichtig ist aber natürlich, dass keine DIV eingesetzt werden, wenn es eigentlich Überschriften seins ollten.

**Comment by xantippe** [comment]
ob statt dem DIV ein Hx steht, ist (mir) relativ egal - was ich auf alle Fälle vermeiden möchte, ist bei Anzeige "Tabellen"eine "aufgeregte und unausgerichtete Anzeige" wie

![shot135](https://cloud.githubusercontent.com/assets/1045318/13391196/3ec71564-ded3-11e5-9c07-fffe002ab024.jpg)

auch das zus. Einfügen der Header-Zeile in jeden Tabellenabschnitt halte ich für nicht brauchbar, da häufig nur einige wenige Items gruppiert werden und die Überschriftzeilen dann überhand nehmen.

das per CSS auszurichten? hmmm... "Gesamtbreite / Anzahl der Spalten = Einzelbreite"? m.E. auch keine optimale Lösung...

**Comment by MacKP** [comment]
Ich glaube ja immer noch, das hier der passende Mittelweg für sehende und nicht sehende die Überschriften in der Tabelle mit `<th>` ist. Ansonsten bekommt man für alle nur eine unzureichende Lösung. Ich kann da @xantippe verstehen, alledings ohne Überschriften geht das mal gar nicht. Mit ist eben nur bei mehr Inhalt richtig gut usw.

**Comment by xantippe** [comment]
zum Thema: http://www.edition-w3.de/TR/1999/REC-html401-19991224/struct/tables.html#h-11.4

**Comment by xantippe** [comment]
**zur Info:** Nachfrage bei @discordier bezüglich Gruppierung und manuelle Sortierung:
auch bei einer Gruppierung kann es eine manuelle Sortierung (innerhalb des "Gruppenblocks") geben.

Somit sieht die Tabelle wie folgt aus:

![shot136](https://cloud.githubusercontent.com/assets/1045318/13419847/8b786e68-df81-11e5-9d5f-0525c224c2e0.jpg)

Eine manuelle Sortierung innerhalb des ```tbody``` zu begrenzen ist u.a. in https://github.com/contao-community-alliance/dc-general/pull/193 gefixt - zusätzlich eine Begrenzungzwischen zwei ```th``` einzubauen (siehe https://github.com/contao-community-alliance/dc-general/issues/198#issuecomment-188724075) sollte kein Problem sein.

Aktuell sehe ich drei Möglichkeiten:
1.) alles so lassen wie es ist und den Anzeigebug fixen (https://github.com/MetaModels/core/issues/936)
2.) die "Grundform" des HTML-Code mit mehreren Einzeltabellen so belassen und statt der DIV für die Gruppierungsanzeige ein Hx verwenden (unterschiedliche Spaltenbreiten je Tabelle müssen dann zwangsweise über ein eigenes, nachzuführendes CSS gemacht werden)
3.) die "Grundform" des HTML-Code als eine Tabelle wie in https://github.com/contao-community-alliance/dc-general/issues/198#issuecomment-188724075 - hier muss der JavaScript-Code für die manuelle Sortierung angepasst werden

**Comment by zonky2** [comment]
wie kommen wir in dem Ticket weiter?

**Comment by zonky2** [comment]
wurde offensichtlich irgendwann gefixt...

![zwischenablage04](https://user-images.githubusercontent.com/1045318/38354612-7d0d1d94-38ba-11e8-817d-7581fa1e1e52.jpg)
