### ISSUE TITLE
bei Eingabefeldern HTML-Attribut maxlenght aufgrund der SQL-Feldgröße setzen

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#200]
bei Eingabefeldern HTML-Attribut maxlength aufgrund der SQL-Feldgröße setzen - z.B. bei Typ "numeric" auf 10 das SQL-Spalte auf int(10) definiert ist - aktuell gibt es keine Beschränkung

**Comment by discordier** [comment]
We could do that.

**Comment by discordier** [comment]
However, we should do this in the rellevant providers.
i.e. https://github.com/MetaModels/attribute_numeric should provide the relevant widget information.

**Comment by zonky2** [comment]
e.g. text element with 255 characters ```varchar(255)```

**Comment by discordier** [comment]
As noted above, the provider of the widget information should supply this information.

**Comment by stefanheimes** [comment]
Per default the DCG have to support it: https://docs.contao.org/books/api/dca/reference.html#evaluation . We have maxlength/minlength/maxval/minval

**Comment by discordier** [comment]
As noted above, it is not the responsibility of DCG to supply this information.
The information is already transferred to the widgets, yet the implementation of the definition builder needs to supply the `eval` data and therefore the attributes have to.

**Comment by zonky2** [comment]
move to https://github.com/MetaModels/core/issues/1500
