### ISSUE TITLE
Reset all filters button at backend

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#202]
Add some button next to the "apply" circle to clear all current filters.
See contao/core#6239

**Comment by xantippe** [comment]
siehe auch https://github.com/MetaModels/core/issues/890

**Comment by discordier** [comment]
Huh? What does the MetaModels frontend filter have to do with the dc-general filter panels?

**Comment by xantippe** [comment]
ahh.. o.k. hatte hier nicht auf BE "umgeschaltet"  ;-)

**Comment by zonky2** [comment]
Feature for Contao 4

**Comment by baumannsven** [comment]
What @zonky2. This can use it for 3.5?

**Comment by zonky2** [comment]
use the funnel with red point
