### ISSUE TITLE
Unterstützung für ACE-Editor einbauen

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#205]
z.Z. wird nur der tinyMCE unterstützt - der ACE fehlt
siehe https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L150

**Comment by xantippe** [comment]
PR: https://github.com/contao-community-alliance/dc-general/pull/206

**Comment by zonky2** [comment]
include at beta35

Thanks
