### ISSUE TITLE
change panel attributes "selected" to HTML5

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#211]
change panel attributes "selected" to HTML5
e.g. https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultSearchElement.php#L179

and adjust all templates e.g. https://github.com/contao-community-alliance/dc-general/blob/master/contao/templates/dcbe_general_panel_filter.html5#L5

**Comment by xantippe** [comment]
add PR: https://github.com/contao-community-alliance/dc-general/pull/212

**Comment by zonky2** [comment]
fixed
