### ISSUE TITLE
editAll: click should the same view as contao

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#219]
at Contao: 
![shot182](https://cloud.githubusercontent.com/assets/1045318/14180522/a2855fe0-f763-11e5-9063-a0fe928205b3.jpg)

hide all without arrow return
![shot183](https://cloud.githubusercontent.com/assets/1045318/14180526/a8c8a6f0-f763-11e5-8330-1fb0705e159b.jpg)

at MetaModels:
![shot184](https://cloud.githubusercontent.com/assets/1045318/14180533/b213cda2-f763-11e5-8a60-6b8f11d793b6.jpg)

![shot185](https://cloud.githubusercontent.com/assets/1045318/14180539/bc924bc8-f763-11e5-9a0c-4b5e4cfaffeb.jpg)

**Comment by discordier** [comment]
You mean, when you are in "Edit multiple" the global operations should get hidden?

**Comment by zonky2** [comment]
yes! in Contao with during operation "editAll" you can see only the return arrow ad "return" (zurück)...

**Comment by zonky2** [comment]
fixed in beta38 with #300
