### ISSUE TITLE
Warning: array_map() expects parameter 1 to be a valid callback, class 'StringUtil' not found

### ISSUE THREAD

**Issue by amenk** [contao-community-alliance/dc-general#222]
I am getting the following error when saving a meta model row

	Warning: array_map() expects parameter 1 to be a valid callback, class 'StringUtil' not found in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php on line 136
	#0 [internal function]: __error(2, 'array_map() exp...', '/home/amk/local...', 136, Array)
	#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php(136): array_map('StringUtil::uui...', Array)
	#2 system/modules/core/library/Contao/Widget.php(798): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Widget\FileTree->validator('6115bfc0-2546-1...')
	#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(451): Contao\Widget->validate()
	#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(257): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
	#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(711): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->processInput(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager))
	#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(602): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
	#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(577): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
	#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
	#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
	#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
	#11 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
	#12 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
	#13 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
	#14 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
	#15 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
	#16 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_la...')
	#17 contao/main.php(20): Contao\BackendMain->run()
	#18 {main}

Here is the composer.lock: https://gist.github.com/amenk/3fac260923a740cfafc10d76f84934c6

**Comment by baumannsven** [comment]
Da gibt es einen Fehler der mit der nächsten beta von DCG gelöst wird.
bzw. wie ich gesehen habe liegt Contao in der Version 3.4.5 vor.
Wenn man auf das aktuelle Contao (3.5.9) updated wäre das Problem auch gelöst.

**Comment by zonky2** [comment]
fixed at DCG 2.0.0-beta35 https://github.com/contao-community-alliance/dc-general/tree/hotfix/2.0.0-beta35
