### ISSUE TITLE
Treepicker hat noch einen JS Bug bei mehrfachem Anwenden nacheinander

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#23]
Treepicker hat noch einen JS Bug, wenn man die Auswahl mehrfach nacheinander ändert und jeweils mit Anwenden bestätigt. Dann wird die Überschrift mehrfach ausgegeben. Zwischendrinn wurde nicht gespeichert!

**Comment by discordier** [comment]
No feedback, closing therefore.
