### ISSUE TITLE
Add color picker

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#255]
Add color picker at 
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php
and
https://github.com/contao-community-alliance/dc-general/blob/master/contao/templates/dcbe_general_field.html5

look at https://github.com/MetaModels/attribute_color/issues/9

**Comment by discordier** [comment]
Has already been implemented as contao-community-alliance/dc-general@6fd36bae620d081f9c49e42ab5f98c45faa33f9d, did it not work for some reason?
What error do you get?

**Comment by zonky2** [comment]
o.k. works fine
![shot200](https://cloud.githubusercontent.com/assets/1045318/15105995/6e1b8a50-15c6-11e6-87c7-441525be2e53.jpg)
