### ISSUE TITLE
ToDo/FixMe for ParentView.php (bail)

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#267]
**What**
Shall we rather bail with "parent not found"?

**Where**
https://github.com/contao-community-alliance/dc-general/blob/6ccec14aec79d839454805e6047ec24eec4a1c06/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php#L103

**Comment by discordier** [comment]
I think we leave it as is.
