### ISSUE TITLE
Broken checkbox

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#277]
See: 

https://github.com/MetaModels/core/issues/1015

**Comment by zonky2** [comment]
you can close or set label to "testing"...

**Comment by zonky2** [comment]
I miss the feature to close the ticket automaticaly after x days like MM

**Comment by discordier** [comment]
Well, give us time to work on it and we can implement the bots. As long as that isn't given, we must do everything by hand. :)
