### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array

### ISSUE THREAD

**Issue by UlrichHolland** [contao-community-alliance/dc-general#279]
Nach Upgrade auf dc-general 2.0.0-beta36 (Contao 3.5.12, composer client 0.16.4) und synccto 3.2.0-beta9, beim Versuch einen Client zu synchronisieren (& Backup Dateien erstellen), werden mehrere Warnings folgender Art ausgegeben:

> Warning: array_key_exists() expects parameter 2 to be array, null given in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php on line 171

**Comment by frontendschlampe** [comment]
yep ... bestätigt ... @stefanheimes sollte darüber bereits Bescheid wissen ... es gibt mehrere, verschiedene Warnings ... @stefanheimes sag Bescheid, wenn du alle brauchst ;-)

@UlrichHolland Fehlermeldungen anzeigen deaktivieren hilft erstmal weiter :-)

**Comment by discordier** [comment]
Bug is in https://github.com/menatwork/syncCto/issues

**Comment by stefanheimes** [comment]
@discordier Sorry i don't think so. I say it is a bug of the DCG. https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/ColorPickerWizardSubscriber.php#L68

You get on this point a null. So it's a dcg problem. I don't want to add in every field a eval, only for the colorpicker. We have to check if we have a eval field or not. If not the function can return.

**Comment by discordier** [comment]
Well, this will enforce to check everywhere if an eval is present.
Maybe we should rather fix this during container build time?

**Comment by stefanheimes** [comment]
1. Wrong PHP documentation. We say it should be a array, but we never init it as array, on this var. See:

https://github.com/contao-community-alliance/dc-general/blob/e8a2805f60904827471eeba2fc4bcbaacb40a38b/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/Properties/DefaultProperty.php#L137

2. The PHP documentation say as return value array and not array|null. See: 

https://github.com/contao-community-alliance/dc-general/blob/e8a2805f60904827471eeba2fc4bcbaacb40a38b/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/Properties/PropertyInterface.php#L194

So we have 2 mistakes, maybe. First we never init the var in a right way in the container or we have to change the return value of the function. After this we can correct the handling in the classes which use this container. 

I think the simplest way would be to correct the wrong var init.

@discordier What do u think ?

**Comment by Saschlong** [comment]
@discordier, @stefanheimes 

This still seems to be an issue. I'm having that problem with dc-general 2.0.0-beta36 and synccto 3.2.0-beta10 (Contao 3.5.6).

**Comment by discordier** [comment]
The commit is in the beta37 hotfix branch and not tagged yet.

**Comment by Saschlong** [comment]
Do you have an ETA on for the next version?

**Comment by discordier** [comment]
I am on the road and will not be back until Tuesday. Maybe @stefanheimes can release?

**Comment by discordier** [comment]
I found the time to tag it non the less. Have fun with the new release. :smile_cat:

**Comment by Saschlong** [comment]
Awesome, thx!
