### ISSUE TITLE
It´s not possible to filter empty values

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#282]
MM a11
DCG b36

![shot233](https://cloud.githubusercontent.com/assets/1045318/15921932/55cbb8a4-2e25-11e6-8684-055159d05c5f.jpg)

**Comment by zonky2** [comment]
PR https://github.com/contao-community-alliance/dc-general/pull/283

**Comment by discordier** [comment]
Has been fixed in https://github.com/contao-community-alliance/dc-general/commit/1c36136837dccf9584e9ed7d8cd64574f1eb9d54#diff-c7fbfdabe9e662ee9ca19502f1430721R165

**Comment by zonky2** [comment]
works fine https://github.com/contao-community-alliance/dc-general/pull/212#issuecomment-233076698
