### ISSUE TITLE
ContainerOnCutCallbackListener args

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#287]
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/ContainerOnCutCallbackListener.php#L42

This listener is for config/oncut_callback or isn´t it?
The original oncut_callback has one parameter for $dc.

The listener method getArgs return the model id and DcCompat. Right way for return args, is return DcCompat only.

@discordier What do you think?

**Comment by baumannsven** [comment]
I have seen in any container callbacks is the same problem.

**Comment by discordier** [comment]
You are right. Current [DC_Table](https://github.com/contao/core/blob/d5138bdb7b4656bd86e8790ba1ec569d5fd5442c/system/modules/core/drivers/DC_Table.php#L803).
However, current [DC_Folder](https://github.com/contao/core/blob/d5138bdb7b4656bd86e8790ba1ec569d5fd5442c/system/modules/core/drivers/DC_Folder.php#L557) is even different, there we have `$source, $destination, $dc`.
I think we stick to the former one and drop the id from there as you suggested.
When filing a PR, you might want to check the other callbacks as well, it might be that in there also some incompatibilities exist.
