### ISSUE TITLE
2.0.0-beta37 - Fatal Error ( MetaModels 2.0.0-alpha13)

### ISSUE THREAD

**Issue by palmi** [contao-community-alliance/dc-general#289]
Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in ***/contao-3.5.14/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 381

with php 5.6.10 don't work
php 7 work

**Comment by firekayne** [comment]
Same problem here.

**Comment by UlrichHolland** [comment]
Same with php 5.6.

**Comment by cliffparnitzky** [comment]
@palmi Please modify the issue title, because the current has no information. The version `2.0.0-alpha` belongs to MetaModels !!!

I have created a PR (#208). @discordier / @stefanheimes What do you think about that?

**Comment by Hauge** [comment]
Bei mir auch. >php5.6 
bie php 7> funktionierts

**Comment by bopsoid** [comment]
Selbes Problem bei mir, konnte ich durch entsprechende Änderung der Zeile 381 auf:

                    && (null !== $properties->getProperty($property)->getExtra()['alwaysSave'])

temporär beheben. Nicht updatesicher, daher kein Dauerzustand.

**Comment by basistom** [comment]
Same problem here.

**Comment by zonky2** [comment]
ich glaube nu hat jeder verstanden, dass es einen Fehler gibt und einen Patch dazu - der ist noch nicht geprüft und eingespielt - das "same here" reicht!

**Comment by discordier** [comment]
Closing this in favor of contao-community-alliance/dc-general#288
