### ISSUE TITLE
Not possible to add a new filter rule to an empty filter set

### ISSUE THREAD

**Issue by cgpro** [contao-community-alliance/dc-general#291]
No error here... I made a short screen capture to demonstrate the problem:
https://vid.me/BUty

Version: dc-general 2.0.0-beta37
Contao: 3.5.15
PHP: 7.0.6

**Comment by cliffparnitzky** [comment]
Additional hint: this seems to be a probleme since dc-general beta37.

**Comment by zonky2** [comment]
may be better headline: "not possible a new filter rule to an empty filter set"

**Comment by zonky2** [comment]
I tested the bug at C 3.2.12 with DCG b37 and MM core a13

its not possible to add the first item at

* rendering setting
* input mask
* fiter set

**Comment by bopsoid** [comment]
It's also not possible to add new attributes if the list is empty (as is after creating a new metamodel).

The icon block in the upper right corner of the light-grey box with the main informationen (name, table name, change date etc.) is completely missing, so that might be the reason why the clipboard arrow is not showing up as well.

**Comment by zonky2** [comment]
we know it!

**Comment by baumannsven** [comment]
This https://github.com/contao-community-alliance/dc-general/commit/39284a1bed7810205abd740a66e5b1424105a269 make fale

**Comment by baumannsven** [comment]
if we are in parent view mode the header buttons not render. seen by the picture.
![ohne titel](https://cloud.githubusercontent.com/assets/2493263/17835987/a8ab527c-6783-11e6-8096-76d20719a355.jpg)

the right header seen by the picture.
![ohne titel 2](https://cloud.githubusercontent.com/assets/2493263/17835989/c9ade44e-6783-11e6-9e1e-f1bd839e5f2c.jpg)


I think the if loop for testing is select mode active in https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php#L316 is bad. I don´t understand check is select mode active by parent view to render the required header buttons for the view.

@discordier what do you mean?

**Comment by baumannsven** [comment]
@discordier I understand check for select mode

**Comment by zonky2** [comment]
@discordier I tested the PR #297 and #298

**Comment by zonky2** [comment]
fixed with DCG beta38 631380a

**Comment by bopsoid** [comment]
Sehr geehrte Kunden,

am 23.08.2016 ist das Büro nicht besetzt. E-Mails werden erst am Abend gelesen und beantwortet.

Ab dem 24.08.2016 bin ich wieder wie gewohnt für Sie da.

Mit freundlichen Grüßen,
Boris Pasek
