### ISSUE TITLE
RTE-enabled Attributes should make use of dbfs

### ISSUE THREAD

**Issue by asaage** [contao-community-alliance/dc-general#292]
I have a longtext attribute with TinyMCE enabled. When i link a file with the help of the TinyMCE-Link-Picker the resulting DB-Entry does store a value something like
```html
 <p>lorem <a href="files/filename.pdf">ipsum</a></p>
```

when i do the same with an ce_text element in an ordinary article
```html
 <p>lorem <a href="{{file::UUID}}">ipsum</a></p>
```
is stored - which is more convenient in terms of rearangements in the filetree.
Unfortunately this can only be observed on db-level (with phpmyadmin)

this issue affects probably other atrributes (translated ones which i never used) so i posted this earlier [here](https://github.com/MetaModels/core/issues/1030).
If it's not a bug then it would be a desirable enhancement.

**Comment by zonky2** [comment]
@asaage pls test this PR: https://github.com/contao-community-alliance/dc-general/pull/293

**Comment by discordier** [comment]
PR has been merged into beta 38

**Comment by asaage** [comment]
https://github.com/contao-community-alliance/dc-general/pull/293#issuecomment-240698818
