### ISSUE TITLE
Cannot use isset() on the result of a function call

### ISSUE THREAD

**Issue by christianromeni** [contao-community-alliance/dc-general#295]
I got this error when using syncCto:

`Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in /home/dev/domain/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 381`

Should be related to this: https://github.com/contao-community-alliance/dc-general/commit/031e3f47cde007691ae3bedbb55eeae69b4d2966#diff-eb7eae3d0cbe8d67765cfea7ff120f2aR381

**Comment by zonky2** [comment]
https://github.com/contao-community-alliance/dc-general/pull/288
