### ISSUE TITLE
Add GitHub templates

### ISSUE THREAD

**Issue by cliffparnitzky** [contao-community-alliance/dc-general#304]
In many issues you will find an answer like "did you tested DCG version x.y" or something else. Maybe the template will reduce the number of this posts a bit. 

Add the files:

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Like in https://github.com/MetaModels/core/pull/984 described.

**Comment by zonky2** [comment]
@cliffparnitzky can you add this as PR

**Comment by zonky2** [comment]
@cliffparnitzky wie siehts aus?

**Comment by zonky2** [comment]
PR https://github.com/contao-community-alliance/dc-general/pull/345

**Comment by baumannsven** [comment]
Merged in 4c5a06eda87d559be93e82a8a4dbf0ffedcef2dc
