### ISSUE TITLE
preload RichTextEditor only at active property

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#308]
change https://github.com/contao-community-alliance/dc-general/blob/e8a2805f60904827471eeba2fc4bcbaacb40a38b/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L154
to active properties

in current time, every filter rule load the RTE

**Comment by discordier** [comment]
How do you know what is active? this is not known in the widget manager.
Only solution is IMO to generate the data when the first RTE field is requested.

@stefanheimes, @baumannsven any objections?

**Comment by zonky2** [comment]
@baumannsven call me we have properies with active state... may be...?

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/pull/309
