### ISSUE TITLE
add checkbox "all chosen items active" 

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#315]
add checkbox "all chosen items active" 
![shot285](https://cloud.githubusercontent.com/assets/1045318/20218745/5c9f2cbc-a826-11e6-877f-bfbd591b07e4.jpg)

**Comment by discordier** [comment]
This is not part of dc-general at all.

It is a private backend module of MetaModels/core.

**Comment by zonky2** [comment]
Mano! woher soll man immer wissen, wer zu wem gehört..;-)
