### ISSUE TITLE
Loading multiple tinymce instances failed

### ISSUE THREAD

**Issue by maik-lampe-easy-media** [contao-community-alliance/dc-general#316]
Check changes made in loadRichTextEditor() in src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php on commit 1551926. Fixed this bei remove the index in line 200 - works fine. Didn't test it with rte enabled.

## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |                                  |
| Contao version:                     |          |                                  |
| MetaModels version:                 |          |                                  |
| Installation via composer:          | (yes/no) |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

(Describe the problem you are having)

## Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on…]

## Describe the behaviour of the application

(Tell us what happens)

## Describe the expected behaviour of the application

(Tell us what should have happened)

## Screenshots

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment]
pls update your issue...

**Comment by maik-lampe-easy-media** [comment]
Sorry, wrong commit number: Commit was 1551926110206a83417d6295c85ff5a6137e963f, take a look at line 200.

If you have more than one longtexts defined with wysiwygin you input-mask, just the last one will be initialized in contao backend.

Remove the index "rte" will append all tiny-instances correct to the frontend.

Key|Value|Comments
---|------|-------
PHP version:|5.6.27|-
Contao version:|3.5.16|-
MetaModels version:|2.0.0.-alpha14|-
Installation via composer:|yes, latest|-	
Installed MetaModels packages:|metamodels/core,metamodels/bundle_attributes,metamodels/bundle_filter|-
DCG version:|dev-hotfix/beta-39|need this, because the ajax sorting was fixed here

**Comment by zonky2** [comment]
I have latest MM core a14 and DCG b38
![shot292](https://cloud.githubusercontent.com/assets/1045318/20561916/43915ff6-b181-11e6-83e8-cb774dc89dc2.jpg)

if you update DCG to a hotfix branch you should update MM-core to the next hotfix at the same time...

**Comment by maik-lampe-easy-media** [comment]
Okay, sounds good. I will close the ticket.

Install dev-hotfix/alpha-15 does not work for me:
```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - metamodels/filter_text 2.1.x-dev requires metamodels/core ~2.0 -> satisfiable by metamodels/core[2.1.x-dev, 2.0.x-dev].
    - metamodels/filter_text 2.1.x-dev requires metamodels/core ~2.0 -> satisfiable by metamodels/core[2.1.x-dev, 2.0.x-dev].
    - Can only install one of: metamodels/core[dev-hotfix/alpha-15, 2.1.x-dev].
    - Can only install one of: metamodels/core[2.0.x-dev, dev-hotfix/alpha-15].
    - Installation request for metamodels/core dev-hotfix/alpha-15 -> satisfiable by metamodels/core[dev-hotfix/alpha-15].
    - Installation request for metamodels/filter_text (locked at 2.1.x-dev) -> satisfiable by metamodels/filter_text[2.1.x-dev].
```

There is no metamodels/* installed anymore.

**Comment by baumannsven** [comment]
See [here](dev-hotfix/alpha-15) to Einstall dev-hotfix/alpha-15

**Comment by zonky2** [comment]
to consider the ```... as 2.0.0``` !

**Comment by maik-lampe-easy-media** [comment]
Installing metamodels dev-hotfix/alpha-15 does not update contao-community-alliance/dc-general, so i updated to dev-hotfix/beta-39 manually. AJAX sorting does work now fine, but tiny does not initialize more than the last one.
````
{
    "require": {
        "contao-community-alliance/composer-client": ">=0.16.4.0",
        "contao-community-alliance/dc-general": "dev-hotfix/beta-39 as 2.0.0-beta39",
        "delahaye/dlh_googlemaps": ">=2.2.0.0,<2.3-dev",
        "madeyourday/contao-rocksolid-custom-elements": ">=1.3.11.0,<1.4-dev",
        "metamodels/bundle_all": ">=2.0.0.0,<2.1-dev",
        "metamodels/core": "dev-hotfix/alpha-15 as 2.0.0",
        "netzmacht/contao-flexible-sections": ">=1.2.1.0,<2-dev"
    }
}
````
![2016-11-23_143047](https://cloud.githubusercontent.com/assets/23698095/20563582/817fc2c8-b189-11e6-89eb-84a32f329ad1.png)

**Comment by zonky2** [comment]
its a bug in beta 39 - after update I see the same...

every textarea with tiny should have a separate script - look at screenshot

![shot293](https://cloud.githubusercontent.com/assets/1045318/20577510/f7ccc1cc-b1c2-11e6-9180-9db4bdbcde4b.jpg)

**Comment by zonky2** [comment]
it´s fixed
