### ISSUE TITLE
Action Events in the Baseview

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao-community-alliance/dc-general#320]
Hi, i wondered if it will be possible to implement something like a Hook inside the switch($actionName) request. 
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php#L149
Something like that maybe??? =)

```
	 case 'dc_action_ext':    
			foreach hook ...   
                	$handler = new hook-class;  
                	$handler->handleEvent($event);    
                	break;
```

Or is there already a way to append a custom event here?

**Comment by baumannsven** [comment]
You can register your own event listener. Use the BaseView class as example.
This class is an event subscriber. After define your own subscriber, must register it.
See here https://github.com/contao-community-alliance/dc-general/blob/master/contao/config/event_subscribers.php.

**Comment by MoniqueHahnefeld** [comment]
@baumannsven ok, thx :) !!! I'll try that.
