### ISSUE TITLE
Cannot addParentFilter in ParentedList mode when in popup

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general#332]
# Description
## Starting point
Model's definition is in `MODE_PARENTEDLIST`.
The list view will be opened in a popup.

## Screenshot
![bildschirmfoto 2017-01-19 um 13 38 35](https://cloud.githubusercontent.com/assets/1284725/22107190/b97a80ec-de4c-11e6-817f-fc25d0e60846.png)

## Error stack trace
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(803): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(872): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(611): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(159): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#6 composer/vendor/contao-community-alliance/dc-general/contao/backend/generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#7 {main}
```

## How to reproduce
With MetaModels. See MetaModels/attribute_tags#49

## Behind the error
See code lines https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-39/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php#L162-L165
A `pid` cannot be fetched from the url when list view is in popup.

**Comment by discordier** [comment]
How do you end up here?

I mean, what would be the correct `pid` in this case which should get transported to the popup?

**Comment by richardhj** [comment]
You gave me an advice. For sure the origin issue was caused by a unsupported use case.

**Comment by discordier** [comment]
I guess so too.
However, we need to catch the exception somehow to hint the unsupported usecase.

We still have many exceptions that are not catched in DCG, we ought to catch them and display a proper error screen then.

**Comment by richardhj** [comment]
The "_Unparsable encoded id value_" exception is a really broad exception. I thought of a "save_callback" exception when trying to save parented metamodel in the tags attribute.
(this is the wrong repository for this note again...)
