### ISSUE TITLE
it´s not possible to override filetree widget template

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#333]
it´s not possible to override filetree widget template because its set to ```privat ```

**Comment by zonky2** [comment]
PR #334

**Comment by zonky2** [comment]
At this time generate the class FileTree any HTML code so we hasn´t a change to modify this with your own template... may be, its a (good?) idea to transfer all HTML generating to the template..??

**Comment by discordier** [comment]
Fixed in 88192fadca80d0603b08b4f920ba2b0a1472d3b4, however you are right and the rest of the HTML should all get transferred to the template.
