### ISSUE TITLE
read only attribute doesn´t work at file widget

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#335]
read only attribute doesn´t work at file widget - see at https://github.com/MetaModels/attribute_file/issues/53

at ```read only``` should
* hide picker button
* disable manual sorting

**Comment by discordier** [comment]
DCg does not know anything about the file attribute. Therefore the file attribute must define the widget information correctly I guess?
Or is this a generic issue with the file picker?

**Comment by zonky2** [comment]
works fine in MM 2.2
