### ISSUE TITLE
beta38 not compatible with Contao 3.2 and php 5.3

### ISSUE THREAD

**Issue by frontendschlampe** [contao-community-alliance/dc-general#336]
In composer.json of dc-general beta38 is written:

```
"require": {
"php": ">=5.3",
"contao/core": ">=3.2,<3.6",
```

https://github.com/contao-community-alliance/dc-general/blob/2.0.0-beta38/composer.json#L34-L36

But this Version is not compatible with the mentioned Contao and php-Version. The version constraints are the most powerful feature of Composer itself and we don't use it.

Please fix this problem and be more careful in the future. :-)

**Comment by frontendschlampe** [comment]
Problem for php 5.3:

https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/RichTextFileUuidSubscriber.php#L80

Problem for Contao 3.2:

https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/RichTextFileUuidSubscriber.php#L86

I have no problem, that there's no support for old Contao or php-versions ... ;-)

**Comment by zonky2** [comment]
fixed with b39 - https://github.com/contao-community-alliance/dc-general/commit/2ab4b4c2df6e51cd5368ea4fbc8a057057dde958
