### ISSUE TITLE
Error if standard not set in sorting/grouping

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#337]
https://github.com/MetaModels/core/issues/1096

**Comment by baumannsven** [comment]
This branch fix the problem https://github.com/contao-community-alliance/dc-general/tree/hotfix/add_group_header

**Comment by zonky2** [comment]
works fine! RTM

**Comment by zonky2** [comment]
@discordier can you merge this pls...

**Comment by zonky2** [comment]
merge in beta39 at 19.04.2017
