### ISSUE TITLE
b39: it´s not possible to create the first new MM 

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#339]
it´s not possible to create the first new MM - may be the new action handlers for list view has´t clipboard for manual sorting

![shot333](https://cloud.githubusercontent.com/assets/1045318/24074264/8b19193e-0c05-11e7-88bd-b317548523bf.jpg)

@baumannsven and I think, it`s a good idea, if we create the first new item, we jump directly at the input mask... (without the "clipboard icon")

**Comment by discordier** [comment]
Won't be possible, DCg does not know if it is the "first" item as you might also just have filtered away all other items.

Yet however, I thought the header was now always visible... I wonder how it got lost.

**Comment by zonky2** [comment]
egal, the main point is, we can create the first MM ;-)

**Comment by baumannsven** [comment]
The header and the headerButtons will not render in [ListViewShowAllHandler](https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-39/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/ListViewShowAllHandler.php) or in [AbstractListShowAllHandler]( https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-39/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php). This two properties are used for inject the clipboard paste before buttons.

Maybe which class is the right for render the properties. I think the AbstractListShowAllHandler is the right.

@discordier what do you mean?

**Comment by zonky2** [comment]
Hi @discordier can you get a answer..?

**Comment by baumannsven** [comment]
The problem is fixed on:
https://github.com/contao-community-alliance/dc-general/commit/5d59c8a52e83991a8fb060780b9f8124f4566556

**Comment by zonky2** [comment]
testet with new attribute - works fine
