### ISSUE TITLE
Hierachie in der 3. Ebene funktioniert von der Darstellung noch nicht richtig

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#36]
Original: https://github.com/MetaModels/DC_General/issues/143

In den ersten beiden Ebenen ist alles super. Sobald aber eine dritte Ebene da ist, wird beim Aufklappen der 2. Ebene die 3. Ebene immer unterhalb des letztens Eintrags der 2. Ebene angezeigt. @discordier du kennst die Install und das Verhalten ;-)

**Comment by xantippe** [comment]
@tim-bec & @MacKP noch aktuell?

**Comment by discordier** [comment]
Wenn der js tree insert bug nun final behoben ist, dann nicht mehr.
klappe doch mal einen tree view auf und schaue ob die Kinder nun an der richtigen Stelle eingefygt werden.
Aktuelleres ticket hierzu ist #89, daher mache ich das hier nun zu.
