### ISSUE TITLE
Apply $GLOBALS['TL_CONFIG']['maxResultsPerPage'] in Metamodels backend listings

### ISSUE THREAD

**Issue by HaraldHubinger** [contao-community-alliance/dc-general#361]
This issue was formerly submitted at metmodels/core and has now been filed here following the suggestion of zonky2.

## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6 and 7.0      |                                  |
| Contao version:                     |     3.5.28     |                                  |
| MetaModels version:                 |      2.2.0    |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description
$GLOBALS['TL_CONFIG']['maxResultsPerPage'] is not applied in backend lists.

The Metamodel at issue contains ~150.000 items.
If Backend-User selects the filterAll-Option in Backend-List the configured value of maxResultsPerPage is not used, so that maximum PHP execution time can be exceeded.

If that is not the intended behaviour it would be useful to apply this setting also to MM-Backend-Lists.

## Steps to reproduce
Create a Metamodel with ~150.000 items. Define a backend listing. Select the filterAll-Option from Filter.

## Describe the behaviour of the application
After exceeding max_execution_time it displays a Server Error (even on a fast machine and minutes of time).

## Describe the expected behaviour of the application
Apply maxResultsPerPage from Settings/localconfig.php

## Alternative step to reproduce
Create a Metamodel with a lesser number of items, but exceeding maxResultsPer Page. Select the filterAll-Option and all items are displayed.

**Comment by zonky2** [comment]
@HaraldHubinger pls check https://github.com/contao-community-alliance/dc-general/pull/363

**Comment by HaraldHubinger** [comment]
Integrated the fix for testing on my installation.

maxItemsPerPage is applied now, and there's no execution timeout anymore, if the value is set properly, but pagination seems broken.

Behaviour of standard DC-listings: set the selector-widget for pagination to "All". Pagination (at the bottom of the page as in selector widget now allows browsing all data in pages of size ['TL_CONFIG']['maxResultsPerPage'].

Behaviour of Metamodels-DC: set the pagination-selector to 'All'. Top left corner pagination-selector widget only allows access to first maxResultsPerPage Items. All other items unaccessible. Pagination on bottom of page is gone.

**Comment by zonky2** [comment]
I deleted my fix - der war Mist ;-)

**Comment by baumannsven** [comment]
Fixed in 3d929bd049aaf3c48377360c9d0c1331f0f83a2d
