### ISSUE TITLE
Beim Toggle-Icon wird das Event "dc-general.model.post-persist" nicht getriggert

### ISSUE THREAD

**Issue by tschupatschups** [contao-community-alliance/dc-general#362]
Klickt man in einem MetaModels Katalog auf das Visibiliy - Icon in der Listenansicht, wird das Event dc-general.model.post-persist nicht ausgelöst.

In der Editier-Ansicht, beim Speichern des Elements schon, dort passt es.

**Comment by zonky2** [comment]
prüfen, ob
* auch andere Events betroffen sind?
* betrifft das allgemein den Toggle bei "Checkbox" oder nur die Option "Veröffentlicht"?

**Comment by tschupatschups** [comment]
1) In der Listen-Ansicht wird zb:
- dc-general.model.pre-delete
- dc-general.model.post-duplicate
wie gewünscht ausgführt.

2) In der Detail-Ansicht wird "dc-general.model.post-persist" wie gewünscht ausgeführt beim Speichern.

Das Event "dc-general.model.post-persist" wird nur nicht beim Toggle-Icon (grünes Auge) in der Listenansicht ausgelöst.

**Comment by baumannsven** [comment]
@zonky2 Kannst du das eventuell mit beta38 gegen testen?

**Comment by zonky2** [comment]
warum beta38 und nicht das aktuelle b40?

**Comment by baumannsven** [comment]
Ich bin der Meinung das dieses Auge für veröffentlichen funktioniert hatte. Es gab von `beta38 => bet39` sehr viele Änderungen. Daher würde ich gerne wissen wie sich das Toggle bei beta38 verhält.

**Comment by zonky2** [comment]
auch in b38 zündet post-persist beim toggle nicht

**Comment by zonky2** [comment]
PrePersistModelEvent geht bei Toggle auch nicht

**Comment by zonky2** [comment]
gefixt mit b42 https://github.com/contao-community-alliance/dc-general/commit/88737b233730f298d5f34729da0dd942685aa8f8
