### ISSUE TITLE
Sorting / Darstellung von Kind-Elementen

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#37]
Original: https://github.com/MetaModels/DC_General/issues/142

Im Sortmode 3 (Sortieren von Kindelementen nach Elternelement) werden leider immer noch alle Items in einem MM angezeigt.
Sortiermodus 4 zeigt dagegen nur die passenden Kindelemente an, bietet dazu dann noch das Elternelement zum Bearbeiten, was dann den Namen 'tstamp.0 05.07.2014 13:57' bekommt, von daher auch etwas unbrauchbar ist an der Stelle ;-)

Viele Grüße

**Comment by denunv** [comment]
Gibt es aktuell eine Möglichkeit bei der Bearbeitung eines Kind-MetaModels ein bestimmtes Attribut des Eltern-MetaModels anzuzeigen? 

Aktuell wird mir bei den Kind-MetaModels immer "tstamp.0  2015-04-01 12:57" angezeigt. Besser wäre, wenn dort z. B. der Titel des Eltern-MetaModels angezeigt wird.

**Comment by tim-bec** [comment]
should be fixed.
