### ISSUE TITLE
It´s not possible to save property if extra empty

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#383]
It´s not possible to save property if extra empty

https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php#L302-L304

see https://community.contao.org/de/showthread.php?68568-Kontrollk%C3%A4stchen-(Checkbox)-l%C3%A4sst-sich-nicht-speichern&p=455107#post455107

**Comment by discordier** [comment]
Fixed in f2589769bff2ad82ef2d7aed127451a693b254ee I suppose.

**Comment by zonky2** [comment]
checked - o.k.
https://github.com/contao-community-alliance/dc-general/commit/f2589769bff2ad82ef2d7aed127451a693b254ee

**Comment by dmolineus** [comment]
Is it alreay part of Contao4?

**Comment by zonky2** [comment]
we must update https://github.com/contao-community-alliance/dc-general/blob/feature/contao4/src/Controller/DefaultController.php#L287
