### ISSUE TITLE
Hotfix 41 Broken

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#390]
The Hotfix 41 is broken. If i try to add a new metamodels i get an error: 

```php
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'languages__langcode' in 'field list' (SELECT id, id, tstamp, sorting, name, tableName, mode, translated, languages, varsupport, languages__langcode, languages__isfallback FROM tl_metamodel WHERE id = '1') thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
```

The systems add the fields from the MCW to the field list of the query. So it's impossible to work with MM. Did we miss some comits or miss we just a test?

Error ist somewhere here: https://github.com/contao-community-alliance/dc-general/commit/d8ddadfedf9994954d1619fe69bed2c8105de0de#diff-a44beaf84941f1a2e0bf53679af2ff87R154

Or is this the problem from my MCW Bugfix ???

**Comment by baumannsven** [comment]
There comes a new Feature for dcg. This in work. Build Properties there are Not a table Column is terrible

**Comment by discordier** [comment]
> Or is this the problem from my MCW Bugfix ???

Yep, that is the culprit but @baumannsven promised to have something ready this evening.
