### ISSUE TITLE
PrePersistModelEvent works different between BE and FE

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#394]
DCG b41

PrePersistModelEvent woks at
* BE: only if any values changed
* FE: every time

**Comment by richardhj** [comment]
Do you have the same attributes in your input mask?

**Comment by zonky2** [comment]
I test it with two different mask and corresponding events... I have a `debug(..)`at both events

**Comment by zonky2** [comment]
hmmm... prePersist should only fire if model changed https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/master/src/View/EditMask.php#L498-L500
