### ISSUE TITLE
Contao FileTree-OrderField inkompatibel

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#40]
Original: https://github.com/MetaModels/DC_General/issues/133

Ich hoffe das hier ist noch das richtige repository. Ich baue gerade eine Sortierbarkeit in das FileAttribut von MetaModels ein. Dabei ist mir aufgefallen, das das FileTree-Widget teilweise inkompatibel ist.
Im Widget wird auf ```$this->activeRecord->id``` verwiesen. Der activeRecord ist beim DC General jedoch nicht vorhanden, wodurch die ID in dieser Query: https://github.com/contao/core/blob/master/system/modules/core/widgets/FileTree.php#L101 nicht gesetzt wird.
Ich denke man bräuchte entweder ein eigenes Widget oder DC General müsste für diese Fälle einen activeRecord bereitstellen.

**Comment by dmolineus** [comment]
We have our own fileTree widget now. f6948925904d29a8a449c752388003996bd77a44
