### ISSUE TITLE
Change naming of license in composer.json

### ISSUE THREAD

**Issue by frontendschlampe** [contao-community-alliance/dc-general#400]
You have to change the license naming from `"license": "LGPL-3.0+"` to `"license": "LGPL-3.0-or-later"` to prevent packagist errors. Actually there's no packagist update.

```The contao-community-alliance/dc-general package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use 'composer validate' to check for errors when you
change your composer.json.```

**Comment by baumannsven** [comment]
This is in https://github.com/contao-community-alliance/dc-general/commit/a0dd75f52b6c72f6670ca9e50963c0f692028a36 changed
