### ISSUE TITLE
Read only select field with chosen

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#414]
If the select declare as chosen and the field is read only, then we must deactivate the chosen option.
This must we do. So if chosen activated the read only do not work in the edit mask.

**Comment by baumannsven** [comment]
@discordier @zonky2 What do you think is the best way for it?

**Comment by zonky2** [comment]
look also at https://github.com/MetaModels/core/issues/567

can we change the field definition an kill the choosen attribute at eval?

**Comment by zonky2** [comment]
is fixed

**Comment by baumannsven** [comment]
I reopen this. This handling is a missing feature.

**Comment by zonky2** [comment]
ok. - in MM 2.2 funktionierts...
