### ISSUE TITLE
[editAll] Attempted to call an undefined method named "handleSelectEditAllAction"

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general#417]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |       7.2   |                                  |
| Contao version:                     |        4.6  |        current dev-master                          |
| DC_General version:                 |       2.1   |                    latest version available              |
| Installation via composer:          | yes |                                  |

## Issue description

Error `Attempted to call an undefined method named "handleSelectEditAllAction" of class "ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\SelectHandler".` occurred in the editAll mode, once you "Go Back".

## Steps to reproduce

1. Go to the Input Screens of one MetaModel
2. Imagine you want to add the css class "w50" to every input widget
3. Edit the input screen via "edit All"
4. Select the attribute "css class"
5. click on edit.
6. You get the message to edit "attribute" as well, as "css class" is dependent on "attribute"
7. Go back to select "attribute"
8. Click on enter, now you have an error screen.

## Describe the behaviour of the application

Error screen. you have to abandon the edit all process.

## Describe the expected behaviour of the application

No error.
Once I started the edit all process all over, it is working. It's is the "go back" that is not supported.

## Screenshots

![untitled](https://user-images.githubusercontent.com/1284725/42132977-595b463a-7d22-11e8-9225-1a9c13e95988.gif)

**Comment by zonky2** [comment]
@richardhj MM 2.0 or 2.1?

**Comment by richardhj** [comment]
2.1

**Comment by zonky2** [comment]
MM 2.0 hat keine Symfony-Console ;-)

**Comment by baumannsven** [comment]
Can the error also be traced in Contao 4.4?  Because DCG 2.1 should support the Contao LTS for the time being

**Comment by zonky2** [comment]
@richardhj you can check this at our MM-2.1-testcase

**Comment by richardhj** [comment]
I can confirm the issue in our test case (Contao 4.4).

![screen shot 2018-07-01 at 13 52 56](https://user-images.githubusercontent.com/1284725/42134147-22b8f460-7d36-11e8-9532-c7fa181ed4a0.png)

**Comment by zonky2** [comment]
@baumannsven ... your turn :(

**Comment by baumannsven** [comment]
I think the problem might be the session.  So I want to wait until the new session treatment is inside

**Comment by zonky2** [comment]
@richardhj pls update your MM 2.1 and clear your session at user profile and test again - I have not found any more errors

**Comment by zonky2** [comment]
reopen - see https://github.com/contao-community-alliance/dc-general/issues/429
