### ISSUE TITLE
[4.6] HttpCache

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general#419]
If I get it right, we should support the HttpCache that comes with Contao 4.6, i.e. the cache invalidation that is done in the DataContainer.

contao/core-bundle#1478
contao/core-bundle#1635
https://contao.org/de/news/rueckblick-auf-das-zweite-core-entwicklertreffen-2018.html
https://github.com/contao/contao/commit/1937a40857151da08bf347a0beee1117b5a939f9

**Comment by zonky2** [comment]
we should discuss this at one of the next MM-calls, how we want to agree this with our "MM-LTS"

**Comment by baumannsven** [comment]
Implement in f9db5fe

**Comment by baumannsven** [comment]
A information for developer.

The namespace for Contao projects starts with ```contao.db.```.
A example http cache tag: ```contao.db.tl_test.4```.
