### ISSUE TITLE
parentview-header-edit uses wrong link and icon

### ISSUE THREAD

**Issue by asaage** [contao-community-alliance/dc-general#420]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | 
| ---------------------------|-------- |
| PHP version:                        |7.1.20|
| Contao version:                     |3.5.35|
| DC_General version:                 |2.0.0-beta47|
| Installation via composer:          |contao-community-alliance/composer-client 0.16.6|
| metamodels/core |2.0.2|

## Issue description

https://community.contao.org/de/showthread.php?71581-Header-im-parentView
https://github.com/MetaModels/core/issues/1242

## Steps to reproduce

1. create standalone MM (mm_parent)
2. create child MM (mm_child)
3. go to edit-mask of mm_child
4. use the Edit-Parent-icon in the header of the child-listing

## Describe the behaviour of the application
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 117
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/ModelCollector.php(146): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/EventListener/ModelRelationship/TreeEnforcingListener.php(77): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->getModel('')
#2 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener->process(Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(705): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php(89): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(55): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#7 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(153): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(75): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#12 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_ha...')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}
```

## Describe the expected behaviour of the application

I'd expect the link to be the same as the edit-link directly in the parent-view (where it is functional) but they differ slightly:
in parent:
**main.php?do=metamodel_mm_xy&act=edit&id=mm_xy::666**
in header of children:
**main.php?do=metamodel_mm_xy&act=edit&id=mm_xy::666&table=mm_xy&pid=**

The empty *pid*-parameter is obviously causing the problem (it works without).

The icon should be *header.gif* instead of *edit.gif*.

**Comment by zonky2** [comment]
We test it with DCG beta37 and beta38, but we can't get that this error

pls check your installation

**Comment by asaage** [comment]
not shure how you did that though...
metamodels/core 2.0.2 requires contao-community-alliance/dc-general ^2.0.0-beta42

The same line of code throws an error [here](https://community.contao.org/de/showthread.php?70688-SyncCto-unter-3-5-34)

**Comment by baumannsven** [comment]
@asaage You do not require dc-general self. The line from dc-general can you remove from your composer.json. And @zonky2 and me have tested in Metamodels with child tables. We do not seen any problems. In our test case this works very fine. Do you can send your table configuration, then we can look where your problem is.
