### ISSUE TITLE
Error on tree-picker (popup widget)

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#422]
MM attribute tags with popup widget

MM 2.1 at create: we can see the tree at picker , but it´s not possible to save (transfer to main page)

**Comment by bezin** [comment]
Unfortunately it is also not possible to unset all values in the picker:

1. Check several Checkboxes in the picker modal. 
2. Save. Works fine. 
3. Uncheck ALL checkboxes in the picker modal.

>>> Update fails with error message `Property tickets (tags) did not accept the value (The values differ. Array element count mismatch. Found 0, expected 1.)`

Unchecking all BUT one checkbox does work. There issue really seems to be an empty value.

**Comment by zonky2** [comment]
fixed
