### ISSUE TITLE
[2.1] Labels not formatted anymore

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general#426]
## Issue description

The labels in the list view are not formatted anymore.
The view differs between 2.1 and 2.0.

## Steps to reproduce

1. Open a MetaModel in the bakend list view

## Screenshots

**v2.0**
<img width="1032" alt="screen shot 2018-08-15 at 22 10 52" src="https://user-images.githubusercontent.com/1284725/44734622-a90beb80-aaea-11e8-983f-3f1069c8931b.png">

**v2.1**
<img width="926" alt="screen shot 2018-08-15 at 22 10 38" src="https://user-images.githubusercontent.com/1284725/44734640-b32dea00-aaea-11e8-80a5-d014276a5864.png">

## Two questions
1. Is someone able to reproduce this?
2. Where does this model formatting regularly happen? As a hint for me to debug.

**Comment by zonky2** [comment]
pls check our test case...

**Comment by richardhj** [comment]
OK.
I found a nasty bug in a third party bundle.
An event listener for the `RenderReadablePropertyValueEvent` was overwriting the default event listener.
