### ISSUE TITLE
Attribute Kopieren zwischen zwei MM führt zu fehlenden Einträgen im Ziel-MM

### ISSUE THREAD

**Issue by Ainschy** [contao-community-alliance/dc-general#427]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.1.19 |                                  |
| Contao version:                     | 4.4.23 |                                  |
| DC_General version:                 | 2.0.48 |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

Kopieren von Attributen z.B. Text von einen MM in ein anderes MM, werden die Attribute in MM angelegt, aber in der MM Datenbanktabelle nicht.

## Steps to reproduce

In einen MM auf Attribute gehen.
Mehrere Bearbeiten -> zu kopierende Attributen auswählen
auf Kopieren und dann zu den Attributen des Ziel MM
dort einfügen -> Attribute sind im BE vorhanden aber in der DB nicht angelegt.

## Describe the behaviour of the application

(Tell us what happens)

## Describe the expected behaviour of the application

(Tell us what should have happened)

## Screenshots

(Add some visual love or even a video if you can)

**Comment by baumannsven** [comment]
I close this issue. This is must be handle metamodels core.
