### ISSUE TITLE
Support negative filter operations

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#43]
Orginal: https://github.com/MetaModels/DC_General/issues/116

The used filter syntax of the DcGeneral does not allow negative filters like (```!=``` or ```NOT IN```). I don't know if there is any reason for that.

It would be great if they are also supported.

**Comment by zonky2** [comment]
@discordier is duplicate of #20

**Comment by zonky2** [comment]
duplicate of #20
