### ISSUE TITLE
[2.0, 2.1] Bug when creating an attribute with the same column name

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#436]
see https://github.com/MetaModels/core/issues/1255#issuecomment-446835562

**Comment by discordier** [comment]
Bug got introduced in https://github.com/contao-community-alliance/dc-general/commit/17446f3db18226380c11ce5166e7219b90e07654#diff-74bdf77094b9a1246f922701deacb509R732
It does store the model with implicit id "null", however, the result is ignored here https://github.com/contao-community-alliance/dc-general/commit/17446f3db18226380c11ce5166e7219b90e07654#diff-11ce102fa1c0f4cff1dfd6be4d793231R71 and therefore we will never see the error.

Assigned to @baumannsven, as he developed it. Nothing we can do from MetaModel side.

**Comment by baumannsven** [comment]
I have look this. By my test for 2.0 their throw an exception for when the column exists

**Comment by baumannsven** [comment]
Fixed in 705efc1220c557a11c73879d09e09a331b471c19
