### ISSUE TITLE
Need better model collector method `collectDirectChildren`

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#442]
## Issue description
in [ModelCollector](https://github.com/contao-community-alliance/dc-general/blob/de136aaaffccd9f9c93d0d1eb0921b4d6883f8ed/src/Controller/ModelCollector.php#L308) we have the method:
 `collectChildrenOf(ModelInterface $model, $providerName = '')`

This is pretty handy but collects recursively. Now in MetaModels I am in need of collecting the direct children of a parent rather than all children and grand children (in contradiction to our need in DCG, where we use it for circular detection in cut&paste).

So I propose adding another method to 2.1:
`collectDirectChildrenOf(ModelInterface $model, $providerName = '')`
Which will only collect the direct children of a passed parent model (simply skipping the recursion).

**Comment by zonky2** [comment]
may be
`collectChildrenLevelOf(ModelInterface $model, $providerName = '', $recursiveLevel)`

**Comment by baumannsven** [comment]
Implement in 1b86dfe3e10e77f1f829fe4fa22824910738c375
