### ISSUE TITLE
Unterschiedliche Deklarationen Feld und methoden values by the default config

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#444]
The field value for the filter in the class is array|null.
The interface means in the getter method return an array. So i think the field declaration is false.
If used the setter for the filter and use null for the setter argument, so the filter is null and not and empty array

**Comment by baumannsven** [comment]
https://github.com/contao-community-alliance/dc-general/blob/703d6ccd9487fa9c988bbc3586c33183dff76e71/src/Data/DefaultConfig.php

**Comment by baumannsven** [comment]
https://github.com/contao-community-alliance/dc-general/blob/703d6ccd9487fa9c988bbc3586c33183dff76e71/src/Data/ConfigInterface.php

**Comment by baumannsven** [comment]
The same problem if found by field sorting too.

**Comment by discordier** [comment]
The value for filter may be `null` when no filter has been set, however, it can not be undone (according to docs) which might be a quirk and therefore we might wand to change the types to support `null|array`.

The declaration of sorting appears to be correct though as it is always an array (even if an empty one) as it is being initialized.

**Comment by baumannsven** [comment]
Fixed in 19f444d
