### ISSUE TITLE
fix toggler

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#452]
fix toggler (reminder @baumannsven)

in MM list of filter rules

toggle from active to inactive - only before page reload e.g. SQL

the icon send 404

**Comment by zonky2** [comment]
kann sich kleiner mehr erinnern, wo das aufgetaucht ist... :(

**Comment by baumannsven** [comment]
Schliesse ich da wir nicht wissen wie wir das reproduzieren sollen.

**Comment by zonky2** [comment]
update description

**Comment by zonky2** [comment]
see https://github.com/MetaModels/core/issues/1298
