### ISSUE TITLE
Error with MM that is used as hierarchy

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#458]
## Checklist before I submit this issue report

I confirm that:
- [ x ] I have tested this with the latest version available
- [ x ] I have checked the Contao community forums for references https://community.contao.org/
- [ x ] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.3.1          |                                  |
| Contao version:                     |        4.4.34   |                                  |
| DC_General version:                 |   Version 4.0.5       |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

Sobald ein Kind Element (hierarchisch) angelegt ist und man veresucht die Backend-Ansicht zu öffnen (Liste), dann bekommt man einen Fehler:

`An exception occurred while executing 'SELECT id FROM mm_targetgroup WHERE ((sourceTable.id IN (?,?,?,?,?)))' with params ["3", "4", "5", "6", "7"]: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sourceTable.id' in 'where clause'`

Wurde von Zonky auch schon in eurer Demo nachgestellt.

## Steps to reproduce

1. Einstellen vom Render-Modus in de Eingabemaske.
2. Erstellen von Items in der ersten Ebene
3. Sobald in einem Item der ersten Ebene ein Item angelegt wird (Kind), dann kann die Ansicht im Backend nicht mehr geöffnet werden.

Stack Trace: Siehe eure Demo

**Comment by discordier** [comment]
Bug introduced in: 91f288aaf4c18787ef5e6f4fab9597e5cd2c122c by prefixing almost everything with `sourceTable`.
This now breaks at [FilterBuilderSql.php](https://github.com/MetaModels/core/blob/6a8b3f0046b877beb485dbc3e91777d47693168d/src/DcGeneral/Data/FilterBuilderSql.php#L124) which has no knowledge that DCG does now want to handle the table with name `sourceTable`. We could of course now fix this there but this will still break anything outside of our scope and therefore this has to be seen as breaking change in DCG.

Hotfix at the moment:
```diff
diff a/core/src/DcGeneral/Data/FilterBuilderSql.php b/core/src/DcGeneral/Data/FilterBuilderSql.php
--- a/core/src/DcGeneral/Data/FilterBuilderSql.php
+++ b/core/src/DcGeneral/Data/FilterBuilderSql.php
         if (!$this->isEmpty()) {
             return new SimpleQuery(
-                sprintf('SELECT id FROM %s WHERE %s', $this->tableName, $this->getProcedure()),
+                sprintf('SELECT id FROM %s sourceTable WHERE %s', $this->tableName, $this->getProcedure()),
                 $this->getParameters(),
                 'id',
                 $this->connection
             );

```

**Comment by MacKP** [comment]
Thx for the Hotifix ;-)
Hotfix works for now. I can use the hierarchical Structur.
Now I see that, the output as 'Popup-Picker' is not relay working for me.
I can see the Childitems in the Parent-Items and outside (it doubles...). All other output variants are working (but not realy a valid solution here).

regards

**Comment by zonky2** [comment]
@baumannsven kommt wieder raus bis 27.02. Abends - alias fliegt raus, dafür table-name als Spalten-Prefix

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/commit/5b6eb75810906d19da62a76049d6764b648c614b
