### ISSUE TITLE
Vorschaubilder konfigurieren

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#459]
## Checklist before I submit this issue report

I confirm that:
- [ x ] I have tested this with the latest version available
- [ x ] I have checked the Contao community forums for references https://community.contao.org/
- [ x ] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.3.1          |                                  |
| Contao version:                     |        4.4.34   |                                  |
| DC_General version:                 |   Version 4.0.5       |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

Wenn man bei MM ein Vorschaubild ausgeben lassen möchte (Backend oder Frontend) und dazu bei den Rednereinstellungen 'Als Bildfeld mit Vorschaubild benutzen' ankreuzt, dann erscheinen '+advanced_legend' und das Klick Verhalten ist sehr seltsam.
Auch beim Entfernen verhält es sich seltsam und man muss andere Checkboxen anklicken als man denkt.

Ist komisch beschrieben, kann aber in eurer Demo nachgestellt werden.

Viele Grüße

**Comment by zonky2** [comment]
transfer to https://github.com/contao-community-alliance/meta-palettes/issues/42

**Comment by dmolineus** [comment]
See MetaModels/core#1280 and MetaModels/core#1281

**Comment by discordier** [comment]
Fixed by MetaModels/core#1281, closing therefore.
