### ISSUE TITLE
Not detected if the widget is a checkbox class with reflection

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#467]
The description see here:

https://github.com/MetaModels/core/issues/1287#issuecomment-474240610

**Comment by richardhj** [comment]
@baumannsven 
Any select widgets do not receive any options anymore. Can you validate this?

We should rethink the method `isGetOptionsAllowed`.
My humble self does not know, which widgets are allowed to receive options and which not.

**Comment by richardhj** [comment]
@baumannsven You have to revert 70351009ac268210eb7d8b8ccfee9fc409e7e54e. `class_parents($widgetClass)` does not contain the actual class, i.e. `Contao\Checkbox`. The condition therefore fails.

**Comment by discordier** [comment]
Ah. Of course, the identity check is missing!

@baumannsven Why did you not add a test for this?

**Comment by baumannsven** [comment]
Oh sorry. I has forgot this. I fix this tomorrow.

**Comment by baumannsven** [comment]
So i have change it. I replace the statement for test with the widget name
