### ISSUE TITLE
Can declare the tree class fix in the tree view?

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#468]
The tree class is in the tree view not change in the moment. I think we can declare the tree class fix.

@discordier What do you mean?

Here:
https://github.com/contao-community-alliance/dc-general/blob/aa16e80aedae574c8857f9b474a60eb894460d11/src/Contao/View/Contao2BackendView/TreeView.php#L430

https://github.com/contao-community-alliance/dc-general/blob/aa16e80aedae574c8857f9b474a60eb894460d11/src/Contao/View/Contao2BackendView/TreeView.php#L653

**Comment by discordier** [comment]
I do not understand what you mean. What is "fix" and why is something fix if it is currently not changed?

**Comment by baumannsven** [comment]
You see the two switch cases in the description on top. This use every times the case 6. So the tree class is in all times the same. So we can remove the switch case.

**Comment by discordier** [comment]
Aaaahh, now I understand.
Yes, in the current form it is a constant evaluation. However, it is only because of a missing feature, namely Contao Tree mode 5.

In previous versions, this was marked with a TODO here to implement this feature

**Comment by baumannsven** [comment]
I opened a new issue for add the missing tree mode #481
