### ISSUE TITLE
Parameter for function call does not match

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#470]
The parameter for call for get the tree collection recursive from the collector not match the same in the declaration.

The rootId is type of string. But the method expects an array.

@discordier What do you think, we do here?

See:
https://github.com/contao-community-alliance/dc-general/blob/aa16e80aedae574c8857f9b474a60eb894460d11/src/Contao/View/Contao2BackendView/TreeView.php#L177

https://github.com/contao-community-alliance/dc-general/blob/eb022142c684371eba78c1ebb3489907206221cd/src/Controller/TreeCollector.php#L325

**Comment by discordier** [comment]
I fail to see where the method expects an array. It appears that it copes with the sting just fine and will rather choke on an array if feeded with.

**Comment by baumannsven** [comment]
You can see it by the tree collector. That would like an array for parameter rootId. TreeCollecter:325

In the tree view called the method and has the rootId as string.

**Comment by discordier** [comment]
Ah, you mean the phpDoc, it's a bit problematic as you only linked the method and not the relevant code section.
Yes, the doc comment has to be corrected.

**Comment by baumannsven** [comment]
Fixed in 88605ec4
