### ISSUE TITLE
Model id parameter temporary overriden

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#474]
See:
https://github.com/contao-community-alliance/dc-general/blob/bfedd4f2254e3d928008ec00bb1aae8de33c4441/src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L132

**Comment by baumannsven** [comment]
Fixed in 8ceeb7a5

**Comment by discordier** [comment]
Reopening after discussion.

This has apparently been introduced by broken merge conflict resolving when merging `override-all`.

@baumannsven will restore the original functionality that was there prior merging this feature.

**Comment by baumannsven** [comment]
The copy handler was damaged after merged.

Fixed in 907361f088d8b96a2d834ef4d3b73b24a1876031
