### ISSUE TITLE
Replace the deprecated backend url builder

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#475]
See:
https://github.com/contao-community-alliance/dc-general/blob/bfedd4f2254e3d928008ec00bb1aae8de33c4441/src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L203

**Comment by zonky2** [comment]
fixed with `\ContaoCommunityAlliance\UrlBuilder\UrlBuilder`
