### ISSUE TITLE
Replace all TL_ constant

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#476]
Example:
https://github.com/contao-community-alliance/dc-general/blob/11790a33acb4e825028f229bd89084ea12369ad2/src/Contao/View/Contao2BackendView/Widget/FileTree.php#L273

**Comment by baumannsven** [comment]
https://github.com/contao-community-alliance/dc-general/blob/11790a33acb4e825028f229bd89084ea12369ad2/src/Contao/View/Contao2BackendView/TreePicker.php#L199

**Comment by baumannsven** [comment]
https://github.com/contao-community-alliance/dc-general/blob/bfedd4f2254e3d928008ec00bb1aae8de33c4441/src/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php#L404

**Comment by baumannsven** [comment]
Fixed in 15c288ed

**Comment by discordier** [comment]
@baumannsven Commit is missing? Did you forget to push?
