### ISSUE TITLE
button "Add new" too much at new input mask

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#486]
button "Add new" too much at new input mask

http://easycaptures.com/fs/uploaded/1229/6638366806.png

and add new MM

http://easycaptures.com/fs/uploaded/1230/2520472416.png

see https://github.com/MetaModels/core/issues/1311

**Comment by baumannsven** [comment]
Fixed in #7f18dd0c

**Comment by baumannsven** [comment]
@zonky2 Test this please. If our test successful, then close this issue.

**Comment by zonky2** [comment]
@baumannsven checked - fixed!
