### ISSUE TITLE
Removing the id parameter for forwarding save and create

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#487]
See https://github.com/contao-community-alliance/dc-general/commit/061e542ff17e6e437b43531bb47d3e12c65e9cc6

**Comment by baumannsven** [comment]
Changed in 6f6a63d0

**Comment by discordier** [comment]
Needs to be reverted, see comment in 061e542 and 6f6a63d

**Comment by baumannsven** [comment]
Revert in c42dedfd2e37cda24a654438d3b0398a1cd37a3a
