### ISSUE TITLE
Improvement of the handling of properties with dependencies during multiple machining

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#488]
Instead of adding the dependent property to the request for editing, it should add these as hidden elements in the input mask. This is because the dependent property must be present when the form is passed, otherwise the data record will not be saved.

**Comment by discordier** [comment]
I am completely lost at what you mean by this.
1. what is a dependent property?
2. what is "machining"?
3. how shall hidden elements be added for dependents? (read: how to render a hidden value for an unknown widget structure?)

**Comment by baumannsven** [comment]
I am in the moment not sure can match dependencies property. So i add all used properties as hidden field.
Hidden fields can declare with the eval key ```hideInput```. This key sets by the widget ```$widget-> hideInput = true```.

**Comment by discordier** [comment]
Are you sure with `hideInput`?
A search in the [Contao Core](https://github.com/contao/core-bundle/search?q=hideInput&unscoped_q=hideInput) does not bring relevant code locations... are you maybe hijacking a widget property here?

**Comment by baumannsven** [comment]
Do show here

https://docs.contao.org/books/api/dca/reference.html

**Comment by zonky2** [comment]
what is with `doNotShow`: "If true the current field will not be shown in "edit all" or "show details" mode."

**Comment by baumannsven** [comment]
Do not show not says the property is a hidden field. This says the property not support in edit all.

**Comment by zonky2** [comment]
ok

**Comment by discordier** [comment]
@baumannsven have you checked the link I gave above? The Contao core is only using this for making TEXT fields into PASSWORD fields - nothing else.

**Comment by baumannsven** [comment]
Changed in 6693d6aa0f973322e1ca30fb7246739feac96fb1
