### ISSUE TITLE
Ajax rendering takes different rendering path for widgets

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#489]
The rendering path for widgets is different when being rendered via `EditMask` and `Ajax3X`.

While the `EditMask` renders via the `ContaoWidgetManager` and calls [`$widget->parse()`](https://github.com/contao-community-alliance/dc-general/blob/b5a9bc9c3267542a0d3058cb457e9ac72519956b/src/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L374), the `Ajax3X` does call [`$widget->generate()`](https://github.com/contao-community-alliance/dc-general/blob/b5a9bc9c3267542a0d3058cb457e9ac72519956b/src/Controller/Ajax3X.php#L343).

This bears a problem as i.e. the `parseWidget` HOOK will not be called for the latter one.

**Comment by baumannsven** [comment]
Fixed in 00fb6fd3706d484d72be661a20a81dde0162a672
