### ISSUE TITLE
Buttons save and save+close does not follow the same flow

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#49]
Original: https://github.com/MetaModels/DC_General/issues/93

I find out, that the save and save+close buttons does not follow the same flow in code. If I press save+close the onsubmit_callback will not be triggered, for example. I need to investigate more time in this, currently I only tried a bit in the backend.

This may be the reason why the problem between MM and Avisota only occurs when pressing save+close.

**Comment by dmolineus** [comment]
I could not reproduce it with the current dev branch. Maybe it's already fixed. I added an onsubmit_callback and it's always triggered no matter which button is used.

Hint: The callback is only triggered when the model has changed as it's mapped to the postPersist PostPersistModelEvent.

**Comment by discordier** [comment]
Considering it fixed then.
