### ISSUE TITLE
Legacy dependencies

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general#491]
Can we get rid of contao-community-alliance/dependency-container and event-dispatcher?

**Comment by discordier** [comment]
Event-dispatcher, I guess so as it registers transparently into the symfony dispatcher.
For the `dependency-container`, we have the problem that we are still providing 4 services that we have to keep for bc reasons.

**Comment by baumannsven** [comment]
Fixed with PR #492
