### ISSUE TITLE
Item ID is missing on PrePersist and PostPersist events, when using the toggle handler

### ISSUE THREAD

**Issue by bezin** [contao-community-alliance/dc-general#502]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |7.2.2|                                  |
| Contao version:                     |4.4.41|                                  |
| DC_General version:                 |2.1.5|                                  |
| Installation via composer:          | yes |                                  |

## Issue description

When listening on Pre- or PostPersistModel event, one can normally distinguish between create and update operations, by checking if the original model has an ID. If the ID is null, the model was created, if it exists, its an update. This does not work with Toggle actions like published state, because the model is cloned in the Toggle Handler, which does not copy the ID by design. 

In the [EditHandler](https://github.com/contao-community-alliance/dc-general/blob/master/src/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php#L113-L114) the ID is manually set after cloning. I propose we do that in the [Toggle Handler](https://github.com/contao-community-alliance/dc-general/blob/master/src/Contao/View/Contao2BackendView/ActionHandler/ToggleHandler.php#L121) as well.

## Steps to reproduce

1. Have a meta model with published attribute
2. Listen to Pre- or PostPersistModelEvent
3. Create an item
4. Toggle published state

## Describe the behaviour of the application

In the event the original model won't have an ID. 

## Describe the expected behaviour of the application

The original model has an ID.

**Comment by discordier** [comment]
Makes sense...

**Comment by zonky2** [comment]
@bezin it´s possible to make a PR?

**Comment by bezin** [comment]
It is already merged?

**Comment by zonky2** [comment]
realy? which number of PR?

**Comment by baumannsven** [comment]
Fix in #503
