### ISSUE TITLE
do not set background color of search input field if empty string

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#506]
do not color search input widget at panel on top if empty string

**Comment by discordier** [comment]
you mean the yellow background? - therefore the "active" class of the search input?

**Comment by zonky2** [comment]
correct - already discussed this with @baumannsven...

**Comment by baumannsven** [comment]
Fixed in d580d17de0d4d922a9fdc5c3664a09f77dcd22c6
