### ISSUE TITLE
Contao change the language key from some action buttons

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#522]
Some language keys change from array to string.

This are i detected:
- [ ] editheader
- [ ] pastenew
- [ ] pasteafter

I implement a check if the key is string or array.
If the key is not a string so i trigger a deprecated notice. In future the key change to string.

**Comment by zonky2** [comment]
@baumannsven add links to code

**Comment by zonky2** [comment]
... sollte gefixt sein in DCG 2.3
