### ISSUE TITLE
Callbacks handle http exceptions as plain exceptions

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#524]
https://github.com/contao-community-alliance/dc-general/blob/ba6b920e1cfba4f997230dd9f5a1d2085e5e1f37/src/Contao/Callback/Callbacks.php#L74

There we must handle the http exceptions differently, as now we kill redirects for eg. from callbacks entirely.

**Comment by baumannsven** [comment]
Fixed in cb3e57fd6c90d776bcaf31bdad0583a5e8264fb8
