### ISSUE TITLE
Test if the event class of mcw exist

### ISSUE THREAD

**Issue by srhinow** [contao-community-alliance/dc-general#527]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.3     |                                  |
| Contao version:                     |      4.9.2    |                                  |
| DC_General version:                 |    2.1      |                                  |
| Installation via composer:          | yes |                                  |

## Issue description
In der composer.json der dc-general-Erweiterung fehlt die Abhängigkeit von menatwork/contao-multicolumnwizard-bundle. So kommt es zu einem Fehler wenn der Installationsprozess durchläuft:

https://pastebin.com/CY2a3Uf4

## Steps to reproduce
install dc-general in pure Contao 4.9 System per composer

**Comment by baumannsven** [comment]
MCW is require in the develop section. This is right. I test i the event class exists.

So this fix the error!

**Comment by baumannsven** [comment]
Fixed in 8c11cad6de0d3045e4a54342ee6e3c31b10e3bb6
