### ISSUE TITLE
eval=>unique wird nur für existierende Records geprüft

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#54]
Original: https://github.com/MetaModels/DC_General/issues/80

Wird ein neuer Record angelegt, wird eval=>unique überhaupt nicht überprüft. Verändert man den Record allerdings anschließend, dann schon.

**Comment by MacKP** [comment]
Funktioniert bei mir auch beim ändern von einem Datensatz nicht. Wird nicht angemeckert (textattribute)

**Comment by discordier** [comment]
Fixed with c1314371d40df31944c95a814da9ec7d08771719
