### ISSUE TITLE
Fix return value of the inverse filter

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#542]
If the inverse filter not configured, then must return null. In the moment comes an empty array back. This is wrong. The documentation says array|null.

**Comment by zonky2** [comment]
what is the inverse filter?

**Comment by zonky2** [comment]
@baumannsven related with https://github.com/contao-community-alliance/dc-general/issues/538 ?

**Comment by zonky2** [comment]
related with #541
