### ISSUE TITLE
Mehrfach bearbeiten

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#55]
Fehlt aktuell noch komplett.

Siehe https://github.com/MetaModels/DC_General/issues/72 https://github.com/MetaModels/core/issues/186
https://github.com/MetaModels/core/issues/532
https://github.com/MetaModels/core/issues/431

**Comment by dmolineus** [comment]
Implementing started here #133.

**Comment by zonky2** [comment]
weiter in Issue #281
