### ISSUE TITLE
Manuelles Sorting (blauer Pfeil)

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#56]
Original: https://github.com/MetaModels/DC_General/issues/69

Wenn man den blauen Pfeil benutzt, muss man ja dann das braune Symbol mit Pfeil nach unten benutzten um das Item an der passenden Stelle einzufügen.
Normalerweise ist das in Contao dann 'unter' dem Element wo man das klickt. Hier ist das dann die selbe Stelle...
Müsste geändert werden um dem Contao Standard zu entsprechen. Dazu bräuchte man dann so ein Einfügen dann noch an Oberster Stelle, damit man auch das Item an erster Stelle einfügen kann.

**Comment by tim-bec** [comment]
feature/clipboard merged, should be fixed

**Comment by asaage** [comment]
Ich meine für den Fall der Listendarstellung (flat) müßte der blaue Pfeil verschwinden. Dafür gibts doch das Draghandle.

**Comment by asaage** [comment]
wtf?!?!?
"tristanlins was unassigned by asaage just now"
würd ich doch niemals tun - kann ich auch gar nicht.
