### ISSUE TITLE
Missing edit pencil in BE list

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#576]
Missing edit pencil in BE list in DCG 2.2

![FireShot Pro Webpage Screenshot #685 - 'MetaModels I mm220 dev metamodel me' - mm](https://user-images.githubusercontent.com/1045318/140703312-0f78afa8-125f-4bea-bcfd-6ee72f78ffa7.jpg)

**Comment by baumannsven** [comment]
Vergleich mal die DCA Konfiguration z.B. mit `tl_news`

**Comment by zonky2** [comment]
braucht #541

**Comment by zonky2** [comment]
und im DCA

```
                'inverse' => [
                    [
                        'local'     => 'pid',
                        'remote'    => 'id',
                        'operation' => '=',
                    ],
                ]
```

gefixt
