### ISSUE TITLE
ArrayCache "Class not found" ab doctrine/cache 2.0

### ISSUE THREAD

**Issue by Ynda** [contao-community-alliance/dc-general#584]
Key                                          | Value       | Comments                              |
| ------------------------------- | -----------| ---------------------------------|
| PHP version:                          |       7.4. x  |                                                 |
| Contao version:                     |     4.9.31   |                                                 |
| DC_General version:              |    2.2.0      |                                                 |
| Installation via composer:     |     (yes)     |                                                 |

## Issue description

Die DcGeneralFactoryCache erweitert Doctrine\Common\Cache\ArrayCache welches ab doctrine/cache 2.0 nicht mehr vorhanden ist.
Das führt zu einem Class not found Fehler.
ArrayCache ist nach meinem Stand bis doctrine/cache Version 1.13 vorhanden und dort schon als deprecated gekennzeichnet..
 * Array cache driver.
 *
 * @deprecated Deprecated without replacement in doctrine/cache 1.11. This class will be dropped in 2.0

Wir benutzen das Paket SyncCto welches wiederum dc_general verwendet.
Aktuelle Contao Versionen benutzen doctrine/cache 2.2+

Ich habe das aktuell mit einem "conflict": {"doctrine/cache": ">=2"} gelöst, was aber bestimmt kein Dauerzustand bleiben sollte. 

Danke und Gruß
Andy

**Comment by zonky2** [comment]
@Ynda teste mal https://github.com/contao-community-alliance/dc-general/blob/release/2.3.0

**Comment by Ynda** [comment]
Hallo zusammen,
diese Problem "frisst" sich so langsam durch weitere Installationen. Wenn nicht als Bug so würde ich es auf jeden Fall als Konfigurationsfehler einstufen.

Danke und Gruß
Andy

**Comment by zonky2** [comment]
@Ynda hast Du denn die 2.3.0 inzwischen getestet?!? das letzte Posting brachte erstmal keine neuen Erkentnisse...

**Comment by Ynda** [comment]
@zonky2 ich bekam kein Feedback zu meinem letzten Posting. Somit steht immer noch die Frage im Raum, wie ich das testen soll, bzw. wie würdest du dabei vorgehen? Dein Link führt immer noch auf eine 404 Seite.

**Comment by zonky2** [comment]
Link aktualisiert...

in Deine composer

```
"contao-community-alliance/dc-general": "^2.3@dev",
```

**Comment by Ynda** [comment]
Perfekt. Das hilft weiter.
Ich habe noch folgendes ergänzen müssen, da sich die dev Pakete sonst nicht installieren lassen.
`
"minimum-stability": "dev",
`
Optional noch ...
`
"prefer-stable": true,
`
Dann habe ich einen Test mit SyncCto gestartet, der erfolgreich verlief, sprich ich konnte wie gewohnt synchronisieren.
Das ist auf jeden Fall keine umfassender Funktionstest der Änderungen, aber für meine Zwecke ist es wohl passend.

Danke und Gruß 
Andy

**Comment by zonky2** [comment]
ich habe mit der `2.3` synCto (Free) mit C 4.9, 4.13 sowie PHP 8.0, 8.1 getestet ... nicht alle Features, aber lief

**Comment by zonky2** [comment]
fixed with #585

**Comment by Ynda** [comment]
Hi Zonky2,

danke für die schnelle Antwort.
Ich weiß ehrlich gesagt nicht, was ich damit anfangen soll. Wenn ich auf den Link klicke bekomme ich einen 404er angezeigt.
Unter branches gibt es eine Version 2.3.0 von dir https://github.com/contao-community-alliance/dc-general/tree/release/2.3.0

Wie soll ich das testen?
Kopiere ich den Code einfach in meine Installation?
Gibt es eine require Anweisung für Composer?
Ich stehe da gerade etwas auf dem Schauch, welches der übliche Weg ist.




Von: zonky2 ***@***.***>
Gesendet: Mittwoch, 20. Juli 2022 17:46
An: contao-community-alliance/dc-general ***@***.***>
Cc: Andreas Bohlig ***@***.***>; Mention ***@***.***>
Betreff: Re: [contao-community-alliance/dc-general] ArrayCache "Class not found" ab doctrine/cache 2.0 (Issue #584)


@Ynda<https://github.com/Ynda> teste mal https://github.com/contao-community-alliance/dc-general/blob/release/2.3.0

**Comment by zonky2** [comment]
Hast Du das mit der aktuellen 2.2.2 nochmal getestet?

Ansonsten in Deine composer.json die Zeile einfügen oder anpassen

`"contao-community-alliance/dc-general": "^2.3@dev",`

siehe z.B. https://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen

**Comment by Ynda** [comment]
Hallo zonky,

hab’s gerade mal bei einer Installation versucht.
Da erscheint unter anderem folgende Meldung im Composer:
Problem 1
9 - contao/news-bundle[4.9.0-RC1, ..., 4.9.9] require php ^7.2 -> your php version (8.0.24) does not satisfy that requirement.
10 - Root composer.json requires contao-community-alliance/dc-general ***@***.******@***.***> -> satisfiable by contao-community-alliance/dc-general[2.3.x-dev (alias of dev-release/2.3.0)].
11 - contao/news-bundle 4.9.11 requires contao/core-bundle 4.9.11 -> satisfiable by contao/core-bundle[4.9.11].
12 - Conclusion: don't install contao/core-bundle 4.9.11 (conflict analysis result)

Das geht dann bis zu …
- contao/news-bundle 4.9.35 requires contao/core-bundle 4.9.35 -> satisfiable by contao/core-bundle[4.9.35].
60 - Conclusion: don't install contao/core-bundle 4.9.35 (conflict analysis result)
61 - contao-community-alliance/translator[2.3.0, ..., 2.3.x-dev] require contao-community-alliance/events-contao-bindings ^4.13 -> satisfiable by contao-community-alliance/events-contao-bindings[4.13.0, 4.13.x-dev].
62 - contao-community-alliance/dc-general dev-release/2.3.0 requires contao-community-alliance/translator ^2.3 -> satisfiable by contao-community-alliance/translator[2.3.0, 2.3.1, 2.3.x-dev].
63 - contao-community-alliance/dc-general 2.3.x-dev is an alias of contao-community-alliance/dc-general dev-release/2.3.0 and thus requires it to be installed too.
64 - contao/news-bundle 4.9.10 requires contao/core-bundle 4.9.10 -> satisfiable by contao/core-bundle[4.9.10].
65 - Conclusion: don't install contao/core-bundle 4.9.10 (conflict analysis result)
66 - contao-community-alliance/events-contao-bindings[4.13.0, ..., 4.13.x-dev] require contao/core-bundle ^4.13 -> satisfiable by contao/core-bundle[4.13.0-RC1, ..., 4.13.x-dev].
67 - Only one of these can be installed: contao/core[2.6.0, ..., 2.11.17, 3.0.beta1, ..., 3.5.40], contao/core-bundle[4.1.0-beta1, ..., 4.13.x-dev, 5.0.0-RC1, ..., 5.x-dev]. contao/core replaces contao/core-bundle and thus cannot coexist with it.
68 - contao/news-bundle 4.9.x-dev requires contao/core-bundle 4.9.x-dev -> satisfiable by contao/core-bundle[4.9.x-dev].
69 - Root composer.json requires contao/news-bundle 4.9.* -> satisfiable by contao/news-bundle[4.9.0-RC1, ..., 4.9.x-dev].
… munter so weiter. Also Contao 4.9.35 ist aktuell installiert und ich habe die PHP 8.0.24 ausgewählt.
Ich verstehe leider überhaupt nicht, was hier gerade das Problem sein soll.
Also PHP8 klappt eigentlich bei keiner Installation, wo SyncCto und alle damit zusammenhängenden Abhängigkeiten installiert sind.

Ich werde das wieder alles zurücksetzen.
Zum Testen bin ich noch nicht mal gekommen.
Sorry.



Herzliche Grüße aus Schorndorf

Andreas Bohlig
______________________________________________
TN34.DE GmbH & Co. KG

+49 7181 985298 13
***@***.******@***.***>
______________________________________________







Von: zonky2 ***@***.***>
Gesendet: Dienstag, 11. Oktober 2022 10:28
An: contao-community-alliance/dc-general ***@***.***>
Cc: Andreas Bohlig ***@***.***>; Mention ***@***.***>
Betreff: Re: [contao-community-alliance/dc-general] ArrayCache "Class not found" ab doctrine/cache 2.0 (Issue #584)


Hast Du das mit der aktuellen 2.2.2 nochmal getestet?

Ansonsten in Deine composer.json die Zeile einfügen oder anpassen

"contao-community-alliance/dc-general": ***@***.******@***.***>",

siehe z.B. https://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen

**Comment by zonky2** [comment]
Deine fehlermeldungen erscheinen etwas komisch, da C4.9 PHP8 kompatibel ist https://github.com/contao/news-bundle/blob/63f39a0dc8b7944c2a214d67b638b0ee6717efd7/composer.json#L24

ggf. ist es einfacher, Du wechselst mit der Frage ins Forum und postest mal Deine composer.json
