### ISSUE TITLE
Button-Funktionen zusammenfassen 

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#60]
Original: https://github.com/MetaModels/DC_General/issues/18

Es gibt zwei Funktionen, welche die Buttons im oberen Bereich erstellen, diese sollten zusammen gefasst werden sowie optimiert werden das alles in einem Array zusammen gefasst wird.

**Comment by zonky2** [comment]
@baumannsven close?

**Comment by baumannsven** [comment]
I must show it.

**Comment by zonky2** [comment]
@baumannsven und "ge-showed"?

**Comment by zonky2** [comment]
original ist closed
