### ISSUE TITLE
Deleting an Parent Item should delete the Children

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#61]
At the Moment we get Child Items without an Parent :(

regards

**Comment by discordier** [comment]
Needs to get implemented at https://github.com/contao-community-alliance/dc-general/blob/5f6502a40f7f2cde2d69156645ede2b25ef12682/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/DeleteHandler.php#L109-L109

**Comment by discordier** [comment]
@baumannsven will give it a shot.

**Comment by asaage** [comment]
https://github.com/contao-community-alliance/dc-general/pull/216
https://github.com/MetaModels/core/pull/998
https://github.com/MetaModels/core/pull/1000

**Comment by discordier** [comment]
Assuming fixed as no reply for almost a month.
