### ISSUE TITLE
Click on the details icon shows an Internal Server Error

### ISSUE THREAD

**Issue by heliflieger** [contao-community-alliance/dc-general#621]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   8.2.11       |                                  |
| Contao version:                     |    4.13.34     |                                  |
| DC_General version:                 |          |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

When click on the details icon at an MM entry an internal server error ate show:

## Steps to reproduce

1. Open MM
2. Click on a MM details icon

## Describe the behaviour of the application

An Exception are thrown: 

`[2023-11-17T21:06:24.818847+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "ContaoCommunityAlliance\Translator\SymfonyTranslatorBridge::try(): Argument #1 ($string) must be of type string, null given, called in ....../contao/vendor/contao-community-alliance/translator/src/SymfonyTranslatorBridge.php on line 37" at ...../contao/vendor/contao-community-alliance/translator/src/SymfonyTranslatorBridge.php line 72 {"exception":"[object] (TypeError(code: 0): ContaoCommunityAlliance\\Translator\\SymfonyTranslatorBridge::try(): Argument #1 ($string) must be of type string, null given, called in ..../contao/vendor/contao-community-alliance/translator/src/SymfonyTranslatorBridge.php on line 37 at ..../contao/vendor/contao-community-alliance/translator/src/SymfonyTranslatorBridge.php:72)"} []`

**Comment by zonky2** [comment]
we must wait for MCW https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/25

**Comment by stefanheimes** [comment]
@zonky2 new Version of MCW is out.

**Comment by zonky2** [comment]
fixed with https://github.com/menatwork/contao-multicolumnwizard-bundle/releases/tag/3.6.3
