### ISSUE TITLE
Contao Page Picker not working after updating from 2.3.9 to >= 2.3.10

### ISSUE THREAD

**Issue by bildschirmartist** [contao-community-alliance/dc-general#636]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  8.2.18        |                                  |
| Contao version:                     | 4.13.43          |                                  |
| DC_General version:                 |  2.3.11        |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

After updating dc-general from 2.3.9 to 2.3.10 or 2.3.11, no PagePicker in the backend works anymore, (e.g. jumpTo for customnav). It is disabled instead:
![image](https://github.com/contao-community-alliance/dc-general/assets/2776658/e237fba2-709b-42b7-bef2-1f6d9a3e1173)

## Steps to reproduce

1. Update dc-general from v. 2.3.9 to 2.3.10 or 2.3.11
2. Edit exisiting customnav module or any module (or create one) with a pagePicker
3. See the disabled PagePicker button

## Describe the behaviour of the application
PagePicker button is disabled

## Describe the expected behaviour of the application

PagePicker should work

## Screenshots

Editing customnav module with dc-general vers. 2.3.11 (wrong behavior):
![image](https://github.com/contao-community-alliance/dc-general/assets/2776658/c5cc9322-608d-4cb1-a123-f57a29dada96)

Editing customnav module with dc-general vers. 2.3.9 (working PagePicker):
![image](https://github.com/contao-community-alliance/dc-general/assets/2776658/0716c629-1b8e-4a90-8275-f0c7eb1030b1)

## Additional Information
I think it has something to do with a problem with the dc-general `PagePickerProvider` that is set as the default `PagePickerProvider`.

**Comment by SimonTeammade** [comment]
We have also been able to reproduce the error in tags 2.3.10 and 2.3.11. 

The error does not occur in tag 2.3.9.

**Comment by zonky2** [comment]
please check PR #637

**Comment by zonky2** [comment]
@bildschirmartist & @SimonTeammade can you check this PR https://github.com/contao-community-alliance/dc-general/pull/637

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/pull/637

**Comment by bildschirmartist** [comment]
> fixed with #637

Thank you very much and sorry for my late response. The fix works for me!
