### ISSUE TITLE
Wrong redirect URL after copy

### ISSUE THREAD

**Issue by MarkejN** [contao-community-alliance/dc-general#639]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    8.2      |                                  |
| Contao version:                     |     4.13.44     |                                  |
| DC_General version:                 |      2.3.12    |                                  |
| Installation via composer:          | yes |                                  |

## Issue description

After copying an item (MetaModels table) I'm redirected to the wrong URL.

## Steps to reproduce

1. In my case I have a table with MetaModels (mm_address).
2. I created a new address (ID: 1) and saved it
3. I clicked the green plus icon in the list view (copy)

## Describe the behaviour of the application

I got redirected to `/contao?table=mm_address&act=edit&id=mm_address::2`. This is a blank page with the title "Dashboard".

## Describe the expected behaviour of the application

I should get redirected to the edit mask `/contao?do=metamodel_mm_address&table=mm_address&act=edit&id=mm_address::2`.

## Issue

As far as I can see this was introduced in https://github.com/contao-community-alliance/dc-general/pull/634:

https://github.com/contao-community-alliance/dc-general/blob/40eb6820aa5cb0a654c79b3e7f8a3422b92114bc/src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L261-L264

https://github.com/contao-community-alliance/dc-general/blob/40eb6820aa5cb0a654c79b3e7f8a3422b92114bc/src/Contao/View/Contao2BackendView/ViewHelpers.php#L259-L260

I think the route name is `contao_backend` instead of `contao.backend`.

**Comment by zonky2** [comment]
I can check this from 01.07.2024 at the earliest...

**Comment by cliffparnitzky** [comment]
I can confirm. I created a PR to hopefully speed up the process for you @zonky2.

Thanks @MarkejN for detecting the code lines.

**Comment by zonky2** [comment]
@MarkejN can you test the PR https://github.com/contao-community-alliance/dc-general/pull/640 ?

**Comment by MarkejN** [comment]
See https://github.com/contao-community-alliance/dc-general/pull/640#issuecomment-2194151605
