### ISSUE TITLE
ReflectionClass::newInstanceWithoutConstructor() is only available since PHP 5.4!

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/dc-general#65]
@discordier how should be solve this? Require PHP 5.4 or changing the code?

http://de2.php.net/manual/en/reflectionclass.newinstancewithoutconstructor.php

https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/Callbacks.php#L123

**Comment by discordier** [comment]
This is not an issue anymore as we are dropping PHP5.3 support.
