### ISSUE TITLE
Bug(?) in Widget::blnSubmitInput bei readonly

### ISSUE THREAD

**Issue by xantippe** [contao-community-alliance/dc-general#67]
Hallo,

möchte man in eine FE-Ausgabe eines MM-Panels nur Daten anzeigen (Select, Checkboxen, Radioboxen) muss man auf readonly gehen statt diabled, damit hier nichts mehr ausgewählt werden kann. 
Durch das vorhandene Hidden-Field wird der Wert aber dennoch auf "nix" gesetzt - wie "Andreas" meint, sollte das nicht der Fall sein...
siehe https://github.com/contao/core/issues/7282#issuecomment-54950242

**Comment by discordier** [comment]
No feedback, closing therefore.
