### ISSUE TITLE
[rework-sorting] Alle Anzeigen funktioinert wird aber falsch angezeigt

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#70]
Es werden alle Items (MM) angezeigt, allerdings ist immer noch 1-30 ausgewählt

**Comment by dmolineus** [comment]
Ich kann dies bei einem Test mit einem einfachen MM ohne Varianten nicht nachvollziehen. Wie kann ich das reproduzieren? Oder ist dies mittlerweile schon gelöst?

**Comment by MacKP** [comment]
Kann ich gerade auch nicht mehr nachstellen. Dafür hab ich beim sorting noch einige andere Probleme (aber da bist du ja glaub ich noch drann +1 !!!) ;-)
Wenn ich das noch mal feststelle, dann mach ich das wieder auf.

**Comment by zonky2** [comment]
gefixt https://github.com/contao-community-alliance/dc-general/commit/20a5b04369253c532e0975ce16dd2f7a9c76bf6c
