### ISSUE TITLE
[rework-sorting] Grouping mit Zahlen klappt gar nicht

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#71]
Beispiel: Sortiert nach Datum (Jahr) ergibt immer nur 1970 als Gruppe (keine weitere Untergruppe)

**Comment by tim-bec** [comment]
gibt es hier nen fortschritt? ich hab bisschen budget um das asap zu fixen...

**Comment by Teelevision** [comment]
In der BaseView wird aus dem Datum das Jahr generiert und anschließend sortiert (wie es scheint).
https://github.com/contao-community-alliance/dc-general/blob/3edfa26992a8ced7c291cd731e806634e39a8604/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php#L331-336
Dort wird davon ausgegangen, dass es sich um ein DateTime object oder Timestamp handelt. Tatsächlich kommt dort ein String im Format YYYY-MM-DD an.
Sollte man annehmen, dass dort immer ein String ankommt, ist das mit dem String ein Fehler oder gibt es einfach beide Fälle mit DateTime/Timestamp und String?

**Comment by Teelevision** [comment]
Die Methode getProperty() vom Model ruft die valueToWidget() Methode des (in diesem Fall Timestamp) Attributs auf (MetaModels). In der valueToWidget() Methode wird der Timestamp in einen String umgewandelt. Das Format bestimmt die Konfiguration, wie es aussieht. D.h. es würde nichts bringen, den String mit dem Datum zu parsen.
https://github.com/MetaModels/attribute_timestamp/blob/a148da651ad90988c2fcf6bd8ab10c11b779f9c7/src/MetaModels/Attribute/Timestamp/Timestamp.php#L139-144

**Comment by Teelevision** [comment]
Der String könnte doch woanders herkommen. Der Wert kann auch durch ViewHelpers::getReadableFieldValue() verändert werden. Jedenfalls scheint es nichts zu bringen, vor dem Event den Wert zu ändern, da es nach dem Event wieder ein Datumsstring ist.

**Comment by dmolineus** [comment]
This issue is mainly caused by the attribute_timestamp of metamodels. The proposed pull request should fix it.

**Comment by discordier** [comment]
No feedback, closing therefore.
