### ISSUE TITLE
[rework-sorting] Sorting per Hand funktioniert noch nicht

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#73]
Sorting per Hand (inklusive Grouping) funktioniert nicht, es wird einfach nicht danach sortiert. Frontend reagiert auch noch nicht dabei.

**Comment by dmolineus** [comment]
Dies wird für MetaModels mit der derzeitigen Implementierung der Sortierung nicht möglich werden Gruppierung + manuelle Sortierung gleichzeitig zu verwenden. Es müssten die kompletten Sortierung und Filterung umgeschrieben werden. 

Meines Erachtens wäre es daher sinnvoll das UI (Eingabemasken, Listen) darauf zu limitieren, sodass beim Benutzer keine Irritationen auftreten (Ausblenden Gruppierung, wenn manuelle Sortierung ausgewählt, Deaktivierung Sortierungs Buttons in der Liste).  

Dies ist allerdings ein Problem von MetaModels und sollte dort in einem Ticket behandelt werden.

Ungeachtet von MetaModels sollte die Kombination von Gruppierung und manueller Sortierung im DCG überprüft werden. Eine manuelle Sortierung sollte dann nur innerhalb der Gruppe möglich sein. Dies ist bei den Icons sowie Drag+Drop zu berücksichtigen.

**Comment by xantippe** [comment]
@dmolineus wie ist den der aktuelle Stand dazu?

gruss

**Comment by xantippe** [comment]
bei meinen Tests MM a10 + DCG b34 funktioniert die manuelle Sortierung (ohne Gruppierung)

**Comment by xantippe** [comment]
"Dies wird für MetaModels ... nicht möglich sein, Gruppierung + manuelle Sortierung gleichzeitig zu verwenden."

Rest funktioniert!
