### ISSUE TITLE
[develop] TinyMCE funktioniert nicht

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#76]
Ich habe bei Contao 3.3.5 das Problem das der TinyMCE nicht angezeigt wurde. Ich habe dann an folgender Stelle https://github.com/contao-community-alliance/dc-general/blob/f0bd490f0d24b6a34a1140ab81b67b93e98606f3/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L343

dies eingefügt
```
$selector = $propertyId;
```
danach geht es.

**Comment by discordier** [comment]
Ticket cleanup.
