### ISSUE TITLE
Port changes from contao/core

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general#82]
The changes made for contao/core/issues/7281 need to be ported to dc-general.

Namely:
https://github.com/contao/core/commit/152410cbcab53d5fa358e96e39856868ae3397ec
https://github.com/contao/core/commit/0c0153120319846dfb8475b21cf5c4838a5b2225

**Comment by dmolineus** [comment]
Pull request got merged 8 days before and no issues reported.
