### ISSUE TITLE
"Paste top" does not work

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/dc-general#84]
Paste elements on top does not work, see Avisota issue [CTO-122](https://avisota.atlassian.net/browse/CTO-122).

**Comment by dmolineus** [comment]
Paste top should work with latest pull request. Already tested with:

 - List view
 - Parent view
 - "Variants" view

Known limitation #126.

**Comment by discordier** [comment]
No feedback, closing therefore.
