### ISSUE TITLE
Rename "IdSerializer" to "Id" or "ModelId"

### ISSUE THREAD

**Issue by tristanlins** [contao-community-alliance/dc-general#85]
We use more and more the `IdSerializer` class instead of the numeric/string ID to pass the ID of a model. I propose to stop using numeric or serialized string IDs and only use the `Id` class as identifier internally.

**Comment by dmolineus** [comment]
Got implemented with e432a9fc1a8e9e71e52f8e0ace2bb7dfa3abccb8.
