### ISSUE TITLE
Incompatibility between DcGeneral an haste

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#88]
If I want to delete anything in an DcGeneral DCA, I get the following message:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Execute callback Haste\Model\Relations::cleanRelatedRecords failed - Exception message: Sorry but there seems to be no valid DataContainer instance! thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/Callbacks.php on line 75
```

**Comment by MrTool** [comment]
Shouldn't this be a ticket at codefog/contao-haste cause the Model/Relations.php throw this error https://github.com/codefog/contao-haste/blob/master/library/Haste/Model/Relations.php#L300 and not DCG - so it seems for me that haste should include a compatibility cause DCG is a layer lower then haste, prove me if i'm wrong.

**Comment by discordier** [comment]
@MrTool in generality you are right but I have partly reverted the change in 7174f8ed15a31bd64886f4f83514395c4d03745b with 40c85ffe86f90843935ba43acede4e74fe5cfdf2.
dc-general now extends the DataContainer again but does not implement the same functionality as Contao and therefore now hints something incorrect.
Sadly we can not solve this in a good way as there is no empty interface hinting a DataContainer.

**Comment by MrTool** [comment]
Isn't this against the rule? Sorry cause i don't understand why an low lvl data layer has to extends from another low lvl data layer which is not an interface. Or is it cause contao currently doesn't support another data layers as the existing ones?

**Comment by discordier** [comment]
Exactly that's the point.
Status quo is that any existing DC is extending from any Contao internal DC.
dc-general is the only one existing that is an entire reimplementation and does not use any code from any other DC.
