### ISSUE TITLE
Hierarchical View: Expand/Collapse defect

### ISSUE THREAD

**Issue by psren** [contao-community-alliance/dc-general#89]
The expand/collapse function of hierarchical lists seems to be defect.

If i open an element its children are displayed at the bottom instead of under the selected item.

Everything okay, than click on the expand button.
![bildschirmfoto 2015-01-29 um 11 08 18](https://cloud.githubusercontent.com/assets/1016798/5955837/71d1a19a-a7a7-11e4-84b1-00e44e7180ce.png)

Children opened at wrong position (look at the collapse symbol)
![bildschirmfoto 2015-01-29 um 11 08 26](https://cloud.githubusercontent.com/assets/1016798/5955836/71d11856-a7a7-11e4-9002-8dac3b0c9a28.png)

**Comment by psren** [comment]
Hups... ich habe mich ausversehen selbst gedoppelt.
Siehe https://github.com/MetaModels/core/issues/667

**Comment by discordier** [comment]
Ist hier aber eigentlich richtiger.

**Comment by psren** [comment]
Okay, das tritt nicht nur auf wenn ich das als einzelne Tabelle einbinde, sondern auch im Picker.
![bildschirmfoto 2015-02-10 um 09 23 33](https://cloud.githubusercontent.com/assets/1016798/6123987/6ca3070c-b109-11e4-88b7-72102636b408.png)

**Comment by discordier** [comment]
Ja, da die betreffenden code stellen genau gleich sind.
Im Picker wird auch nur ein "normaler" Baum gezeichnet, nur dass der statt icons zum bearbeiten eben die radio/checkboxen hat.

**Comment by discordier** [comment]
Should be fixed with ba80328212aa905fefdf31b1ed88becc2066eb15.

**Comment by stefanheimes** [comment]
Should be fixed with ba80328212aa905fefdf31b1ed88becc2066eb15

**Comment by stefanheimes** [comment]
Not fixed!

**Comment by stefanheimes** [comment]
Okay, remove some old code from the first version. We have two templates for the tree, one with files as class and another with folder as class. But both have the same structure. So we only need one js version to inject the elements. 

So with the next version the problem should be solved.

**Comment by xantippe** [comment]
Beim Verschieben und Einfügen sind die umgezogenen/neuen Knoten auch vor reload an der richtigen stelle...

der Baum sieht aber ab Ebene 2..3 nicht "hübsch" aus - ich habe mir den Quelltext mal angesehen und wollte das fixen... habs schnell wieder zu gemacht ;-)

![shot124](https://cloud.githubusercontent.com/assets/1045318/13189859/41dca118-d75a-11e5-8eb0-845c5ac1164b.jpg)

**Comment by discordier** [comment]
Dann sollte man hier optisch nochmal nacharbeiten? Oder sehen die immer so aus?

**Comment by xantippe** [comment]
werde ich testen...

**Comment by xantippe** [comment]
test mit DCG  	dev-hotfix/2.0.0-beta34 (bb67abb3)

ja, sieht noch so aus

![shot154](https://cloud.githubusercontent.com/assets/1045318/13527183/8894d3c4-e20d-11e5-9bb1-3fde75d12cb4.jpg)

Bugfis wäre z.B. in https://github.com/contao-community-alliance/dc-general/blob/develop/contao/html/css/generalTreeView.css

```diff
.tl_pagetree_content {
-    width: 94%;
+    width: 93%;
}
```
 zu setzen - das ```.tl_left > a``` nimmt mit dem marging-right: 5px zu viel Platz weg

**Comment by discordier** [comment]
aber das nun mit 1% zu fixen fyhlt sich komisch an... 5px != 1%...
Evtl. sollte sich hier mal einer von unseren CSSlern @frontendschlampe oder @MacKP generell mit dem layout von DCG befassen und das "durchstylen"

**Comment by xantippe** [comment]
hatte gestern längeres Gespräch mit @stefanheimes zu dem Thema - Frage war, ob der von Contao "übernommene" HTML-Aufbau so ideal ist - Stichwort: keine "sauber" verschachtelten ULs sonder "Childs" sind in "LI-Siblings"...

**Comment by MacKP** [comment]
Wie wäre es damit, das hier erst mal die Core Variante genutzt wird (jaja, ich weiß.. ist nicht perfekt). Der Vorteil: es wäre konsistent und würde eventuell endlich mal funktionieren...
Dann kann man immer noch schauen, was man da tolles neues draus machen kann. Eventuell auch als PR für den Core?

**Comment by xantippe** [comment]
was meinst Du mit "Core-Variante"? es wird in MM die "DCG-Variante" genutzt, die vom HTML-Aufbau auf der Contao-Variante aufbaut (deshalb stehen da CSS-Klassen wie "tl_files..." usw. drin)...

Aufgrund der Probleme bzw. der schwierigen Problembehebung ist die Frage, ob man mit einer "besseren" HTML-Struktur leichteres Spiel hat?

**Comment by MacKP** [comment]
Ah, das hab ich dann falsch verstanden. Da ist dann für mich die Frage, was da den Unterschied zum Core ausmacht (wenn es genau gleich ist, dürfte das Verhalten so ja nicht sein). Mal schauen...
Viele Grüße
PS: Ist mir schon klar, das hier der DCG genutzt wird...

**Comment by xantippe** [comment]
warum ist das Ticket geschlossen?
mit DCG b34 habe ich 

* Formatierungsfehler ab Ebene 3
* teilweise falsches Aufklappen der Childs

=> siehe Video (leider ist der Ton "verschwunden") http://screencast.com/t/QyLGog8X4Hq

**Comment by discordier** [comment]
@xantippe The problem with the incorrect adding of child elements should have been fixed with d244dd6 according to @stefanheimes.

Reopened as the video shows evidence that it has in fact not been fixed.

**Comment by zonky2** [comment]
look at https://github.com/MetaModels/core/issues/805#issuecomment-218442293

**Comment by zonky2** [comment]
fixed https://github.com/contao-community-alliance/dc-general/pull/418
