### ISSUE TITLE
Fatal Error beim Speichern 

### ISSUE THREAD

**Issue by Schnubl** [contao-community-alliance/dc-general#95]
Nach einem Update bekomme ich beim Speichern egal ob Neu oder Bearbeiten folgenden Fehler:

Fatal error: Call to a member function validate() on a non-object in /www/htdocs/xxx/xxxxxxx/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php on line 807

Es kann somit kein Eintrag mehr bearbeitet oder hinzugefügt werden.

Contao 3.3.5
metamodels/attribute_rating 	dev-tng (7413817a)
metamodels/bundle_all 	dev-master (f5892747)
metamodels/core 	dev-tng (40b57f81)

**Comment by MrTool** [comment]
Auf welcher Version läuft der dc-general

**Comment by Schnubl** [comment]
contao-community-alliance/dc-general 	2.0.0-beta22

**Comment by Schnubl** [comment]
Mit dem heutigen Nightly ist dieser Fehler behoben!
