### ISSUE TITLE
Datenverlust beim SubmitOnChange

### ISSUE THREAD

**Issue by davidmaack** [contao-community-alliance/dc-general#96]
Wenn ich eine Checkbox aktibiere, die eine Subpalette nachlädt (MM), gehen die Werte alle Selects und File-Attribute verloren.
Wenn man nicht speichert, sondern einfach den Datensatz neu lädt ist alles OK, aber in der Regel wird der Redakteur einfach Speichern und somit die Daten löschen.

**Comment by MrTool** [comment]
siehe auch metamodels/core#712

**Comment by xantippe** [comment]
aktuelle Test: Contao 3.5.6 mit MM 2.0.0-alpha8

Selects und File-Auswahl bleiben auch bei Reload erhalten - siehe Screenshots

siehe auch #493

Ticket kann m.E. geschlossen werden...

![shot26](https://cloud.githubusercontent.com/assets/1045318/12074505/5188a8d2-b158-11e5-8cb3-3d1c41cfc4f8.jpg)

:::::::::::::::
![shot27](https://cloud.githubusercontent.com/assets/1045318/12074507/5bcfd6da-b158-11e5-9fde-7eca8a159ede.jpg)

:::::::::::::::
![shot28](https://cloud.githubusercontent.com/assets/1045318/12074508/60eaf9d8-b158-11e5-9646-ed6b2729b239.jpg)

:::::::::::::::
![shot29](https://cloud.githubusercontent.com/assets/1045318/12074509/673b0472-b158-11e5-9c4e-db5bea127adb.jpg)
