### ISSUE TITLE
Fatal error: Unparsable encoded id value: '1' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 140

### ISSUE THREAD

**Issue by artiwebdesign** [contao-community-alliance/dc-general#97]
Leider bekomme ich in Contao 3.4.4 beim klick auf das Plus zum Erweitern der Sprachen im MetaModel auch eine Fehlermeldung. Hat irgendwer eine Idee was ich da machen kann?
Ist die neuste MetaModel Version aus dem Composer 2.0.x-dev ...

<pre><strong>Fatal error:</strong> Uncaught exception <strong>ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException</strong> with message <strong>Unparsable encoded id value: '1'</strong> thrown in <strong>composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php</strong> on line <strong>140</strong><br><br>
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(71): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('1')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(51): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#8 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodels')
#9 contao/main.php(20): Contao\BackendMain->run()
#10 {main}</pre>

![image](https://cloud.githubusercontent.com/assets/8812297/6398897/2f26419e-bdef-11e4-9d0c-8b3759b32550.png)
![image](https://cloud.githubusercontent.com/assets/8812297/6398906/3e329412-bdef-11e4-957e-d06620c0f447.png)

**Comment by Zeromax** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by artiwebdesign** [comment]
Sorry, jetzt ist es etwas übersichtlicher ;)

**Comment by dmolineus** [comment]
Should be solve by 581c9c76c79c742143a3d4a101239e81961c5f30. Please test it and confirm that it's solved.

**Comment by discordier** [comment]
No feedback, closing therefore.
